mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt

Use requireArguments() instead of arguments!!

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/model/Item.kt
mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt

Toggle Player items

---

docs/USAGE.md

Add TOC to docs

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt

* Add voice recognition
* Hide widget value in title
* Don't show legend for single items if legend is not set

Improve chart activity

---

mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt

Remove the redundant list of transports sorted by priority. That list
was out of date (Bluetooth was missing), so BT tethering connections
were filtered out before they could reach the when block. Since priority
sorting is done in ConnectionFactory anyway, we don't need the priority
logic anymore anyway.

Simplify and fix API 26+ connection detection logic.

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt

Fix dynamic icons

---

mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt

Fix selection of sitemap in demo mode

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/widgetlist_iconvaluetext.xml

Remove newline from value view

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Just to be sure the server has the latest device information.

Run background tasks after boot

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Check if intent is resolvable before starting activity

---

mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt

Let's see if this closes #1807

Retry loading shared prefs

---

mobile/build.gradle

Change appintro to new repo url

---

mobile/build.gradle
mobile/src/main/res/values-night/themes.xml
mobile/src/main/res/values/themes.xml

Update AboutLibraries to version 8

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt

Don't show state in NFC success toast

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt

Overload funs more Kotlin like

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt

Respect search when refreshing item picker

---

mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
mobile/src/main/res/drawable/ic_nfc_black_180dp.xml
mobile/src/main/res/layout/fragment_writenfc.xml
mobile/src/main/res/values/strings.xml

Show success toast after writing tag

---

docs/USAGE.md
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/ic_power_plug_grey_24dp.xml
mobile/src/main/res/drawable/ic_power_plug_off_grey_24dp.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Send charging state to server

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
mobile/src/main/res/values/strings.xml

Basic UI does this as well and it's good to debug some auto refresh issues

Show snackbar on SSE subscription failure

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt

Remove unneeded @JvmOverloads

---

mobile/src/main/res/values/strings.xml

Add example to notification channels

---

README.md

Update Travis URL in Readme

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Don't show state in color picker title

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt

Day theme:
* Light nav bar on Oreo and above
* Otherwise black nav bar
Night theme:
* Nav bar has the same color then the background
Closes #1873

Theme navigation bar like background

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt

and search term matches zero items.
Fixes #1914

Fix issue when refreshing item picker

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Hint for debugging data saver

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Close drawer on back press

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/widgetlist_videoitem.xml
mobile/src/main/res/values/strings.xml

Show an error message and retry button instead of showing nothing. Also add a loading indicator.

Handle video player errors

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/drawable/ic_home_search_outline_grey_340dp.xml

New icon for server discovery

---

mobile/src/main/java/org/openhab/habdroid/background/NfcReceiveActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Minimum api is 21, so no need to check for it.

Remove unneeded checks for api 21

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt
mobile/src/main/res/values-v29/arrays.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/values/themes.xml

Add amoled/black theme

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/res/layout/activity_main.xml

Define gravity of loading indicator in xml

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt

Don't use our own function for hiding prefs

---

mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt

Fix infinite loop when binding Google Maps view.

---

mobile/src/main/res/values/styles.xml
mobile/src/main/res/values/themes.xml

Fixes #1947
Also changes background color and use round corners.

Improve text readability in dialogs

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Alarm clock: Send UNDEF if no alarm is set

---

mobile/src/main/res/layout/widgetlist_webitem.xml

Fix WebView height when set to WRAP_CONTENT

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/ic_cloud_upload_outline_grey_24dp.xml
mobile/src/main/res/values-v29/arrays.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml
mobile/src/main/res/xml/preferences_device_information.xml

Fixes #1918
Also remove helpHint from ItemUpdatingPreference, because it's the same hint for every pref.

Move device information prefs to subpage

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt

Fixes #1965
@maniac103 Do you remember why you chose `TaskStackBuilder` over a simple `startActivity()`?

Use same animation when opening prefs

---

mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Remove unused `@Suppress`

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

WorkManager: Use enqueueUniqueWork

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt

Correctly theme dialogs

---

mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt
mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt

Fix crash when scheduling periodic workers

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt

Accept short URL's (without host and port)

Accept short URL's (without host and port)

---

docs/USAGE.md
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/res/values/strings.xml

Ask for permission when enabling 'Send wifi name'

---

.github/ISSUE_TEMPLATE/bug-report.md
mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
mobile/src/main/res/values/strings.xml

The build date doesn't say anything about the version, so I removed it.

Remove build date from About

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Color picker: Always send HSV

---

docs/USAGE.md

Docs: Add note about min api for DND mode

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Fix crash when reading SSID on Android 8

---

CONTRIBUTING.md
README.md

Also update the formatting to match the "one line per sentence"
guideline from openhab-docs and add one FAQ.

Update links in README and CONTRIBUTING

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/res/layout/activity_chart.xml
mobile/src/main/res/layout/widgetlist_chartitem.xml
mobile/src/main/res/values/attrs.xml

Aims at fixing double chart image loading mentioned at https://github.com/openhab/openhab-android/issues/2022#issuecomment-637770137

Optimize image loading

---

docs/USAGE.md

The rule was written by @cweitkamp: https://community.openhab.org/t/alarmclock-doesn-t-fire/87202/16
Closes #1618

Docs: Send Alarm clock to DateTime item

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/CustomInputTypePreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/DeviceIdentifierPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/NotificationPollingPreference.kt

See https://github.com/openhab/openhab-android/issues/1982#issuecomment-623946382

Fix a violating the open-closed principle with dialog preferences

---

mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt

Don't use app name as notification title

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

... and without action.
Closes #2068

Reduce snackbar duration for snackbars with info purpose

---

docs/USAGE.md

Docs: Add label and icon to device info items

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Fix UninitializedPropertyAccessException in MainActivity

---

mobile/src/main/res/values/strings.xml

See https://community.openhab.org/t/android-app-beta/41382/242

Improve quick settings tile hint

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Request background location access for sending SSID

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

For details, see individual commit messages.
Closes #2066

Fix image refresh and image/video pause/resume behavior

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/res/drawable/ic_ceiling_light_black_24dp.xml
mobile/src/main/res/drawable/ic_floor_lamp_black_24dp.xml
mobile/src/main/res/drawable/ic_lamp_black_24dp.xml
mobile/src/main/res/drawable/ic_outdoor_lamp_black_24dp.xml
mobile/src/main/res/drawable/ic_sofa_black_24dp.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml

Add a few more tile icons

---

mobile/src/main/java/org/openhab/habdroid/model/Item.kt

Remove transformation instructions from state description pattern.

---

mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt

Restore tile states and start event listener after update

---

docs/USAGE.md
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

Allow sending charging state to switch Items

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Increase logging when getting charging state

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix slider crash on UNDEF items

---

mobile/build.gradle

Reverts openhab/openhab-android#2102
This causes a crash every time the MapView is shown:
````
org.openhab.habdroid.beta E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.openhab.habdroid.beta, PID: 11638
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
at org.osmdroid.config.DefaultConfigurationProvider.load(DefaultConfigurationProvider.java:337)
at org.openhab.habdroid.ui.MapViewHelper.createViewHolder(MapViewHelper.kt:55)
at org.openhab.habdroid.ui.WidgetAdapter.onCreateViewHolder(WidgetAdapter.kt:187)
at org.openhab.habdroid.ui.WidgetAdapter.onCreateViewHolder(WidgetAdapter.kt:98)
at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
at …
```

Revert "Bump osmdroid-android from 6.1.6 to 6.1.7"

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/res/layout/widgetlist_imageitem.xml
mobile/src/main/res/values/attrs.xml

Fix handling of large bitmaps

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt

Item picker: Show snackbar if demo mode is on

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/res/values/strings.xml

Send dev info: Show last update in pref summary

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

Fix image widget sizing issues

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt

Badge shortcuts on API 24 and below

---

mobile/src/main/java/org/openhab/habdroid/background/BroadcastEventListenerService.kt

Fix crash when starting event listener

---

mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
mobile/src/main/res/values-hdpi/dimens.xml
mobile/src/main/res/values-mdpi/style.xml
mobile/src/main/res/values/dimens.xml
mobile/src/main/res/values/styles.xml
mobile/src/main/res/values/themes.xml

Fix blurred outline of switches with mapping

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/ui/widget/AutoHeightVideoView.kt

Let's see if this fixes #1802.
With this PR I wasn't able to reproduce the crash on my device.

Update Androidx Media2 to 1.1.0-alpha01

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix retry button of video widget

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/EventListenerService.kt
mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/res/values/strings.xml
mobile/src/test/java/org/openhab/habdroid/background/EventListenerServiceTest.kt

Improve strings related to event listener and dev id

---

mobile/src/main/res/values/strings.xml

See https://github.com/openhab/openhab-android/pull/2136#pullrequestreview-464926327

Improve device identifier string

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/res/drawable/ic_outline_radio_24dp.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml

Add radio icon to quick tiles

---

mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

I'd like to separate them from regular settings.

Prefs category for debug messages

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

ItemUpdateWorker: Extract correct class from bundle

---

mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt

About: Change docs link to Android page

---

docs/USAGE.md

Replace tabs with spaces in docs

---

mobile/src/main/java/org/openhab/habdroid/util/Util.kt

Fix isEmulator() for newer versions

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

After the initial connection was successful, every error lead to an error notification. With this commit the worker retries to send the item update in a few cases, e.g. on timeouts.
The http codes I added sound like a retry could help: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
Fixes #2163

Retry worker in a few cases

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

Add action to cancel workers

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt

Don't clear icon cache on manual refresh and increase HTTP cache size.
Fixes #1230

Don't clear icon cache on manual refresh

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/PeriodicSignalImageButton.kt
mobile/src/main/res/layout/widgetlist_coloritem.xml

Add long press behavior for color widgets

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt

Before it showed "Last update was null..." if the last update was
unsuccessful.

Show only successful work infos in item update pref summary

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Hide all connection related snackbars on connection change

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/values/strings.xml

This is more useful than 'Open settings'.
Fixes #656

Suggest to visit status.openhab.org if there's an issue with myopenhab

---

mobile/build.gradle

Bump com.google.android.material to 1.2.1

---

mobile/build.gradle
mobile/src/foss/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/foss/java/org/openhab/habdroid/util/RemoteLog.kt
mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
mobile/src/full/java/org/openhab/habdroid/util/RemoteLog.kt
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/res/layout/item_updating_pref_dialog.xml
mobile/src/main/res/values/strings.xml

Android 11 Support

---

mobile/src/main/res/values/strings.xml

Remove unused strings

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt

Hide shortcut action if pinning shortcuts is unsupported

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Add confirm leave dialog to tiles prefs

---

mobile/src/main/AndroidManifest.xml

See https://developer.android.com/guide/webapps/webview-privacy

Opt out of webview usage statistics collection

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Replace two toasts with snackbars

---

mobile/build.gradle

Reduce target api to 29 for now

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.kt
mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
mobile/src/main/java/org/openhab/habdroid/util/MjpegStreamer.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt
mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
mobile/src/test/java/org/openhab/habdroid/util/SyncHttpClientTest.kt
mobile/src/test/java/org/openhab/habdroid/util/UtilTest.kt

https://github.com/openhab/openhab-android/commit/b6428dceed9314652eb0100897e891c08161cf23 changed the import order. Since then many PRs include an optimization of imports.
With this PR I optimized all remaining files.

Optimize imports

---

mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/res/values/strings.xml

Start discovery in intro

---

docs/USAGE.md

Signed-off-by: Markus Storm <markus.storm@gmx.net>

remove openhabianpi from docs due to active misuse of openhabianpi.com

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix slider crash

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/NotificationPollingPreference.kt
mobile/src/main/res/values/strings.xml

"Touch" suits better for touch screens than "click".
https://github.com/openhab/openhab-android/pull/2261/files/d4256770f39ebb54407f951d92fb272707f6d643#diff-5ca5147a9754be194f0298defed14367

Replace click with touch in strings

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/CustomInputTypePreference.kt
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences_local_connection.xml
mobile/src/main/res/xml/preferences_remote_connection.xml
mobile/src/main/res/xml/preferences_server.xml
mobile/src/main/res/xml/preferences_tile.xml

Handle whitespaces in EditText based on the pref

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/ic_nfc_grey_24dp.xml
mobile/src/main/res/drawable/ic_outline_looks_3_black_24dp.xml
mobile/src/main/res/drawable/ic_outline_looks_3_grey_24dp.xml
mobile/src/main/res/drawable/ic_view_dashboard_outline_grey_24dp.xml
mobile/src/main/res/menu/left_drawer.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml
mobile/src/main/res/xml/preferences_drawer_entries.xml

Make drawer entries configurable

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt

Move client certificate callback handling to main thread.

---

docs/USAGE.md

Add Tasker error code example to docs

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
mobile/src/main/java/org/openhab/habdroid/model/Item.kt
mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.kt
mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt
mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt

https://android-developers.googleblog.com/2020/11/the-future-of-kotlin-android-extensions.html

Use new kotlin-parcelize gradle plugin

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Update server name after changed based on SSID

---

mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt

Fixes #2305 and #2320
@MikeJMajor @lolodomo Can you please test the following apk?
- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk
[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/5669285/mobile-foss-beta-debug.zip)

Make label optional

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Allow clearing url in prefs

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Update AppIntro to 6.0.0

---

.github/workflows/commit-release.yml

Create release commit with GitHub Actions

---

docs/USAGE.md

Taken from @cweitkamp: https://community.openhab.org/t/alarmclock-doesn-t-fire/87202/19

Update alarm clock rule to work with openHAB 3

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix NPE in WebViewHolder

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt

Implement JS interface of OH3 UI

---

mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

See https://github.com/openhab/openhab-android/issues/2358#issuecomment-757358601

Ignore canceled cloud checks

---

.github/workflows/commit-release.yml

Update branch name in CI

---

mobile/build.gradle

Bump target API to 30

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt

Don't go back to sitemaps when app opened by shortcut

---

.github/workflows/build.yml

Don't run CI on Crowdin branch

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/InfoPreference.kt
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences_device_information.xml
mobile/src/main/res/xml/preferences_local_connection.xml
mobile/src/main/res/xml/preferences_remote_connection.xml
mobile/src/main/res/xml/preferences_tile_overview.xml

Add hint where to add API token

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Apply dark mode to OSM

---

mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Increase logging in Uri?.openInBrowser()

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt

Demo mode: Fix HABPanel title and hide server selection

---

mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Reduce "invalid URL" log messages

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt

The image wasn't loaded, because the website had a DDOS protection based
on the user agent.
Fixes #2266

Pretend to be Chrome

---

.github/workflows/deploy-apk.yml

Restore Google Maps API key

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Hide server selector if there's no server configured

---

mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Use context.showToast() instead of calling Toasty directly

---

.github/workflows/deploy-apk.yml

Fix release CI

---

mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt

Make getActivityThemeId() an extension function

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt

Reduce data access warnings

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Hide widget divider for invisible widgets

---

mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

Scale fallback image like progress image

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Hide slider tick marks if there are many possible values

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

Respect image scalling preference on image items with state

---

mobile/build.gradle
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/ui/FullscreenImageActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/activity_image.xml
mobile/src/main/res/menu/fullscreen_image_menu.xml

It includes support for zooming the image.
See #320

Add fullscreen activity for images

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Hide frames with no visible children

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/res/values/strings.xml

Play compliant location permission requests

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

Log image urls on error

---

mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
mobile/src/test/java/org/openhab/habdroid/testUtils/RetryRule.kt

See #2385
Source: https://mromeh.com/2017/12/04/implement-retry-in-unit-test/

Retry unit tests

---

mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
mobile/src/test/java/org/openhab/habdroid/core/connection/DefaultConnectionTest.kt

Send auth when API token is used

---

crowdin.yml

Satisfy DCO for Crowdin commits

---

mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt

Don't hide auto generated widget label

---

mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt

Add logging for read/save server configuration

---

mobile/build.gradle

Bump build tools to 30.0.3

---

mobile/src/main/java/org/openhab/habdroid/model/WebViewUi.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/HabpanelWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/Oh3UiWebViewFragment.kt
mobile/src/main/res/values/strings.xml

It's also possible to create multiple shortcuts for the same UI now.
This is a prerequisite for having shortcuts that link to subpages.

Add ability to set shortcut title

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/test/java/org/openhab/habdroid/util/UtilTest.kt

Save subpage in WebView UI shortcuts

---

docs/USAGE.md

Use openHAB 3 URLs for voice commands docs

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/RecyclerViewSwipeRefreshLayout.kt

Fix swipe-to-refresh if first item is hidden

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

The work is retried regardless of the current retry count when a timeout
occurs or one of the `RETRY_HTTP_ERROR_CODES` is returned.

Fix case where ItemUpdateWorker retries forever

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Add preference to set start page

---

mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt

https://developer.chrome.com/docs/devtools/remote-debugging/webviews/

Make WebViews debuggable

---

mobile/src/foss/res/values/strings.xml
mobile/src/main/res/values/strings.xml

Move ACRA related strings to foss flavor

---

mobile/src/main/res/layout/widgetlist_switchitem.xml

Fix inconsistent switch widget height

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Fix tile prefs not always closed

---

mobile/src/main/res/layout/activity_log.xml
mobile/src/main/res/values/styles.xml
mobile/src/main/res/values/themes.xml

Fix incorrectly themed FAB

---

mobile/src/foss/java/org/openhab/habdroid/util/CrashReportingHelper.kt
mobile/src/full/java/org/openhab/habdroid/util/CrashReportingHelper.kt
mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt

Also catch `java.security.UnrecoverableKeyException`

Retry secret prefs fetch in more situations

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt
mobile/src/main/res/values/strings.xml

See https://github.com/openhab/openhab-android/issues/2547#issuecomment-827884218

Hint user about notifications not available on home.myopenhab.org

---

mobile/src/main/java/org/openhab/habdroid/ui/FullscreenImageActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix FullscreenImageActivity crash when image too large

---

mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt

Redact Firebase Token in LogActivity

---

build.gradle
mobile/build.gradle

https://developer.android.com/studio/build/jcenter-migration

Remove JCenter

---

.github/workflows/deploy-apk.yml

Reverts openhab/openhab-android#2577

Revert "Bump svenstaro/upload-release-action from 2 to 2.2.1"

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Ignore alarms set by Samsung calendar

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt
mobile/src/main/res/xml/preferences_server.xml

Fix SslClientCertificatePreference summary

---

mobile/build.gradle

Bump androidx.security:security-crypto to 1.0.0

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/res/values/strings.xml

Fixes #2000
I'm not sure about the prefs title, it could be dropped.

Add hint why connection is marked as insecure

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt

Add logging when loading website in AbstractWebViewFragment

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt
mobile/src/main/res/layout/text_input_pref_dialog.xml
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/xml/preferences_local_connection.xml
mobile/src/main/res/xml/preferences_remote_connection.xml

Suggest myopenhab.org for remote servers.

Add suggestions to UrlInputPreference

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/res/drawable/ic_fan_black_24dp.xml
mobile/src/main/res/values/arrays.xml
mobile/src/main/res/values/strings.xml

Add fan and text icons for quick tiles

---

docs/USAGE.md
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/EventListenerService.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/ic_watch_outline_grey_24dp.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences_device_information.xml
mobile/src/test/java/org/openhab/habdroid/background/EventListenerServiceTest.kt

Redirect Gadgetbridge Device Actions to openHAB server

---

mobile/src/main/AndroidManifest.xml

https://community.openhab.org/t/android-app-beta/41382/365
https://tasker.joaoapps.com/pluginslibrary.html

Tasker: Don't declare plugin as condition

---

mobile/src/main/res/values/strings.xml

Make settings_gadgetbridge_howto_url non-translatable

---

mobile/src/main/java/org/openhab/habdroid/ui/FullscreenImageActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Refresh FullscreenImageActivity

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Suppress data access warnings on known WiFi SSID access

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt

Fix NPE if Base64 bitmap is null

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Use server name as fallback in app bar

---

mobile/src/main/java/org/openhab/habdroid/core/connection/CloudConnection.kt

IMO this is a server side issue, but it's in a stable version and
therefore mitigate it also in the app.
The exception is stilled logged in case of false detection of a cloud
server.
Fixes #2662

Treat server with invalid notification api as non-cloud

---

mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Don't treat about:blank as new host

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt

Add TODOs to `@Suppress` introduced by Android 11

---

mobile/src/test/java/org/openhab/habdroid/background/TileServicesTests.kt

Re-implement TileServicesTests

---

.gitignore

This file includes local paths.

Git ignore .idea/deploymentTargetDropDown.xml

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/spinner_prompt.xml

Same text color, font and size.
Closes #537

Format selection widgets like setpoints

---

mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt

Allow some mixed content in WebViews

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fixes #2378
@Trysupe I tested all your sitemap examples from #2378 and it looks good now, but maybe you can also test it:
[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/7148593/mobile-foss-beta-debug.zip)
- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

Fix widget divider visibility

---

.editorconfig
.github/dependabot.yml

Dependabot: Ignore dependencies in config file

---

mobile/src/main/res/xml/preferences_local_connection.xml
mobile/src/main/res/xml/preferences_remote_connection.xml

Trim user name and password in settings

---

mobile/src/full/java/org/openhab/habdroid/util/CrashReportingHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Make crash reporting optional

---

mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt

Don't redact myopenhab.org in LogActivity

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
mobile/src/main/java/org/openhab/habdroid/model/Item.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt

Use these tags to select a device type for device control.
Closes #2742

Parse semantic tags

---

mobile/src/foss/java/org/openhab/habdroid/util/CrashReportingHelper.kt
mobile/src/full/java/org/openhab/habdroid/util/CrashReportingHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/Util.kt

Replace isFull/isFoss checks by more meaningful functions

---

mobile/src/main/java/org/openhab/habdroid/util/Util.kt

Fix emulator check on Android 12 emulators

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Fix widget creation

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Fixes #2775
@cwihne Can you test the following apk?
- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk
[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/7692040/mobile-foss-beta-debug.zip)

Fix voice commands

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Mark more work requests as important

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
mobile/build.gradle

Update Android Studio

---

mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt

Fix multiple SSIDs migration

---

mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Hide crash reporting preference in FOSS flavor

---

docs/USAGE.md

Fixes #2724
Rule created by @rkoshak.

Use rule template for alarm clock rule

---

mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionExceptions.kt
mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/WifiSsidInputPreference.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/layout/pref_dialog_wifi_ssid.xml
mobile/src/main/res/values/strings.xml

Add ability to restrict local connection to specific SSIDs

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/WifiSsidInputPreference.kt

Fix build issue in WifiSsidInputPreference

---

mobile/src/main/res/values/strings.xml

The new wording matches the system preferences.

Improve wording of screen timeout pref

---

mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
mobile/src/main/res/menu/log_menu.xml

Make log searchable

---

mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt

Fix writing tags

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Show item state in frame

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Cancel pending workers when new state matches last successful update

---

docs/USAGE.md

Explain limitations of getting the alarm clock

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Implement forceAsItem-option for charts

---

docs/USAGE.md

Link and its label were reversed
Signed-off-by: Felix Schneider <fs@felix-schneider.org>

DOCS: Fix broken link

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Ignore alarm sent by null

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

... in ItemsControlsProviderService.kt to display Item Name in Android Device Controls

Added .setSubtitle(item.name) 

---

docs/USAGE.md
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/EventListenerService.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/ic_baseline_bluetooth_disabled_grey_24dp.xml
mobile/src/main/res/drawable/ic_baseline_bluetooth_grey_24dp.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences_device_information.xml

Send list of connected bluetooth devices

---

mobile/src/main/AndroidManifest.xml

Explicitly declare some features as not required

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

Use server name as structure in item control

---

mobile/src/main/java/org/openhab/habdroid/model/Item.kt

Suppress unused warnings for Item.Tag

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/PeriodicItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/BasicItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/NfcItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences_homescreen_widget.xml

Show item state in widget

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ColorItemActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/activity_color_picker.xml
mobile/src/main/res/values/strings.xml

Item control: Show color picker on long press tile

---

mobile/src/main/res/values/strings.xml

Fix typo in "item_tag_equipment_ceilingfan"

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

Add more voice command debug messages

---

mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Suppress warning in PackageManager.isInstalled()

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Requested in https://community.openhab.org/t/android-app-org-openhab-habdroid-home-screen-launcher-kiosk-mode/136499

Add ability to set app as launcher

---

mobile/src/foss/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt

Bug introduced by https://github.com/openhab/openhab-android/commit/417acc2d98e4f862c5881dad2302bd27ea06d796#diff-213515902329aa3da737b520a0fe64f82225bc3e5f223077189e8ca49acd755eR351

Fix showing FOSS notification pref

---

mobile/src/main/AndroidManifest.xml

Fix crash when allowing beta version to be set as launcher

---

docs/USAGE.md
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Don't crash on missing phone permissions

---

mobile/src/main/java/org/openhab/habdroid/model/Item.kt
mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt

Support command options

---

.github/ISSUE_TEMPLATE/release.yml

I'll create one issue for each release and replace #549.

Add release template

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/res/values/strings.xml

Declare audit attribution tags in manifest

---

mobile/src/main/java/org/openhab/habdroid/core/connection/CloudConnection.kt

Don't print expectable parsing error as error in log

---

mobile/src/main/res/xml/network_security_config.xml

http is fine for local connections.

Remove warnings in network config

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/res/xml/backup_rules_v31.xml

Specify backup rules for Android 12

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Don't retry if app isn't started anymore

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Fix crash when sending null alarm time

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/res/drawable/ic_baseline_check_24.xml
mobile/src/main/res/menu/prefs_save.xml
mobile/src/main/res/menu/server_editor.xml

Default toasts are used for 3 major Android versions now.

Remove Toasty dependency

---

mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationWorker.kt
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ColorItemActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/SelectionItemActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ConnectionSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ServerEditorFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/TileSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Fix NoSuchMethodError introduced in #3014

---

mobile/build.gradle
mobile/proguard-rules.pro
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerOnePane.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerTwoPane.kt

On a test device this reduced the app size from 60MB to 30MB.

Minify app

---

mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Fix sending alarm clock

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Fix back press closing app

---

docs/USAGE.md

Remove deprecated alarm clock rule template

---

.editorconfig
.github/workflows/build.yml
.github/workflows/commit-release.yml
.github/workflows/deploy-apk.yml
.github/workflows/labeler.yml
.github/workflows/validate-strings.yml

Restrict token access in GitHub Actions

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/DeviceControlFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml
mobile/src/main/res/xml/preferences_device_control.xml

* Move to a subscreen
* Add hint where to find the tiles
* Add a pref 'auth required'
* Hide if feature isn't supported
Closes #2970

Improve device control settings

---

.github/workflows/deploy-apk.yml

Remove permissions from workflow "Deploy APK on GitHub"

---

mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt

Hide summary notification for hidden channels

---

mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/layout/activity_item_picker.xml
mobile/src/main/res/layout/fragment_notificationlist.xml
mobile/src/main/res/layout/fragment_status.xml
mobile/src/main/res/layout/fragment_webview.xml
mobile/src/main/res/layout/fragment_widgetlist.xml
mobile/src/main/res/layout/fragment_writenfc.xml
mobile/src/main/res/layout/widgetlist_data_saver.xml
mobile/src/main/res/layout/widgetlist_mapitem_no_position.xml
mobile/src/main/res/layout/widgetlist_videoitem.xml
mobile/src/main/res/values/colors.xml

Improve text color contrast ratio

---

mobile/src/main/res/xml/preferences.xml

Allow pref titles to use multiple lines

---

mobile/src/main/res/layout/tasker_item_picker_config.xml
mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml

Use default text style in outline buttons

---

mobile/src/main/res/values/strings.xml

Add http 404 error string

---

mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Update launcher pref title and summary

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
mobile/src/main/res/layout/activity_chart.xml

Fix chart in ChartWidgetActivity

---

mobile/src/main/java/org/openhab/habdroid/model/Item.kt

Add Item type 'Call'

---

mobile/src/main/res/values-w600dp/dimens.xml
mobile/src/main/res/values-w750dp/dimens.xml
mobile/src/main/res/values/dimens.xml

Make the number of shown switches depending on the screen width.

Adjust hidden section switches

---

mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

While at it, I also cleaned up some more coroutine invocations.

Use coroutines for server property fetch logic

---

mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/VoiceWidget.kt
mobile/src/main/res/drawable/widget_dark_background.xml
mobile/src/main/res/drawable/widget_light_background.xml
mobile/src/main/res/layout/widget_item_update_dark_no_text.xml
mobile/src/main/res/layout/widget_item_update_dark_text.xml
mobile/src/main/res/layout/widget_item_update_light_no_text.xml
mobile/src/main/res/layout/widget_item_update_light_text.xml
mobile/src/main/res/layout/widget_item_update_light_text_small.xml
mobile/src/main/res/layout/widget_item_update_preview.xml
mobile/src/main/res/layout/widget_voice.xml
mobile/src/main/res/layout/widget_voice_with_icon.xml
mobile/src/main/res/values-v31/dimens.xml
mobile/src/main/res/values/dimens.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/item_update_widget.xml
mobile/src/main/res/xml/voice_widget_info.xml
mobile/src/main/res/xml/voice_widget_with_icon_info.xml

* Add preview layout
* Add description
* Use corner radius provided by the launcher
* Use launcher UI for edit button instead of our own
Fixes #2995

Improve widgets on Android 12

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/AbstractSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ConnectionSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/DeviceControlFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/DrawerEntriesMenuFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/SendDeviceInfoSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ServerEditorFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/TileOverviewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/TileSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt
mobile/src/test/java/org/openhab/habdroid/util/PreferencesUtilTest.kt

Move AbstractSettingsFragment to a new file

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt

Fix crash when creating widget

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/values-w600dp/dimens.xml
mobile/src/main/res/values-w750dp/dimens.xml
mobile/src/main/res/values/dimens.xml

Improve hidding section switches

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Fix ClassNotFoundException: ServerProperties

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

Fix all warnings in ItemsControlsProviderService.kt

---

mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt

Fix crash in bottom sheet slider

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

As a Job can only run (and be cancelled) once, widgets depending on the CoroutineScope only worked when initially attached, but ceased to work once they were recycled. Fix this by having the scope as member variable instead of subclass and by recreating the scope when attaching the widget.

Fix coroutine handling in sitemap widgets

---

mobile/src/main/res/layout/widgetlist_frameitem.xml

Don't hide frames without label

---

mobile/src/main/res/layout/bottom_sheet_selection.xml

Add ScrollView to selection bottom sheet

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt

Limit number of updates in Setpoint slider

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/drawable/ic_next_track_themed_24dp.xml
mobile/src/main/res/drawable/ic_playpause_themed_24dp.xml
mobile/src/main/res/drawable/ic_previous_track_themed_24dp.xml
mobile/src/main/res/layout/widgetlist_playeritem.xml
mobile/src/main/res/values/strings.xml

The server side rendered player controls both look ugly and take more space than needed. Replace them by a dedicated layout.

Use special layout for player widget

---

mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/drawable/frame_chip_background.xml
mobile/src/main/res/layout/drawer_header.xml
mobile/src/main/res/layout/widgetlist_frameitem.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Implement an option to use dynamic colors

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
mobile/src/main/res/values/strings.xml

Allow creation of home screen widgets for read-only Items

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

These tiles can display item states.

Allow read-only items in device controls

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt

Also remove "Detail" from `AbstractWidgetDetailBottomSheet` as it makes the name longer and doesn't really add context.
Closes #3168

Expand bottom sheets by default

---

README.md

Mention test track in Google Play

---

mobile/src/main/res/values/strings.xml

Remove redundant whitespace in string

---

mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt

https://community.openhab.org/t/notification-icon/143770

Cache notification icons

---

mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt

Fix issues when leaving widget creation

---

mobile/src/main/res/values-night/themes.xml
mobile/src/main/res/values/colors.xml
mobile/src/main/res/values/themes.xml

Fix window background on API <= 28

---

mobile/src/main/res/values-night/themes.xml
mobile/src/main/res/values/colors.xml
mobile/src/main/res/values/themes.xml

Fix text color in intro

---

mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt

Don't declare notifications as event related

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/res/menu/main_menu.xml

Makes it easier to test things with MTM, e.g. theming.

Add debug-only setting to clear MTM keystore

---

mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml

Reduce text padding inside a section switch

---

mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java

Similar to #3215, but this time for MTM

Fix MTM dynamic theme

---

mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
mobile/src/main/res/values-v33/strings.xml
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Requires to apply default preference values in `OpenHabApplication`.
Closes #3185

Enable dynamic theme by default

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/SendDeviceInfoSettingsFragment.kt
mobile/src/main/res/values/strings.xml

Refactor permission check logic, add WebView permission UI

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt

Use slider bottom sheet also for roller shutters

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Allow using theme colors as label/value colors

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt

Fix Google Maps bottom sheet crash

---

mobile/src/main/res/xml/locales_config.xml

Replace Norwegian by Norwegian Bokmal

---

docs/USAGE.md

Review docs

---

.github/workflows/build.yml

Reduce build time from ~20m to ~9m.

Use matrix for different build flavors

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt

Just pass through this parameter like Basic UI does.
Closes #3246
Closes #3250

Support parameter "yAxisDecimalPattern" of Chart widgets

---

docs/USAGE.md
mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/HabpanelWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/Oh3UiWebViewFragment.kt
mobile/src/main/res/values/strings.xml

Replace user-facing strings: "openHAB 3 UI" => "Main UI"

---

mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt

Fix crash when opening notification list

---

mobile/src/main/java/org/openhab/habdroid/ui/ColorItemActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt

Round HSB values

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/HabpanelWebViewFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/Oh3UiWebViewFragment.kt

Fix error detection for Main UI

---

mobile/build.gradle

Remove duplicate entries in about libraries

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Add setting to hide icons

---

mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt

Fix icon name parsing

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

Improve Player items in device control

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Fix pref 'Show icons'

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt

SVGs in MainActivity follow DayNight mode changes

---

mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt

Catch exception in AbstractTileService

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/drawable/baseline_question_mark_24.xml

Display a question mark on switches with 'null' state

---

.github/dependabot.yml

That reduces/bundles the mails and notifications caused by Dependabot.

Run Dependabot weekly

---

.github/workflows/build.yml

Don't fail complete matrix if one job fails

---

mobile/src/main/AndroidManifest.xml

Don't add ColorItemActivity and SelectionItemActivity to back stack

---

mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt

Filter alarm clock on Android 12+

---

mobile/src/main/res/drawable/list_selector.xml
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/values/themes.xml

Theme list selector

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt

Don't require reload for 'Show icons' change to take effect

---

mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/InfoPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/ItemUpdatingPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/NotificationPollingPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/PrimaryServerPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/SslClientCertificatePreference.kt

Treat them like the info icons that aren't disabled as well.
Closes #3402

Don't disable help icons

---

mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/foss/res/layout/widgetlist_mapitem.xml
mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
mobile/src/full/res/layout/widgetlist_mapitem.xml
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/res/layout/widgetlist_chartitem.xml
mobile/src/main/res/layout/widgetlist_icontext_for_heavy_data.xml
mobile/src/main/res/layout/widgetlist_imageitem.xml
mobile/src/main/res/layout/widgetlist_videoitem.xml
mobile/src/main/res/layout/widgetlist_videomjpegitem.xml
mobile/src/main/res/layout/widgetlist_webitem.xml

Show label and icon for all Widgets

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt

Support for that field was added in openhab/openhab-core#3403
Fixes #3466

Update 'iconcolor' field from SSE events

---

mobile/src/main/AndroidManifest.xml

Fix keyboard hiding input widget

---

mobile/src/main/res/layout/widgetlist_switchitem_compact.xml

Fix cut button in compact mode

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

There can be an optional group in the topic path.

Fix parsing of SSE topic for groups

---

mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt

Similar to https://github.com/openhab/openhab-android/pull/3490, but also for brightness in floats, e.g. `23.0`.

Parse float as brightness

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/NotificationChannelPreference.kt
mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/PrimaryServerPreference.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Add option to remove all custom notification channels

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetSlider.kt

Increase precision when using slider with float

---

mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt

Don't set app name in notifications

---

.github/workflows/deploy-apk.yml

See https://github.com/r0adkll/sign-android-release/issues/84

Specify build tools for deployment

---

mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt

Reduce duration of missing notification permissions snackbar

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Limit button width in Buttongrid

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Use 24h mode for time picker if appropriate

---

mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
mobile/src/main/res/values/strings.xml
mobile/src/main/res/xml/preferences.xml

Use the existing 'Clear image cache' setting, rename it and move it to the trouble shooting section.
It might help in some situations, like #3601

Clear WebView cache

---

mobile/src/main/res/values/strings.xml

Hint for basic auth when 401 occurs

---

.github/workflows/lint.yml

It uses ktlint for Kotlin.
See #3640

Run super linter in CI

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

See https://github.com/openhab/openhab-core/issues/3430

Support new Slider parameter: releaseOnly

---

mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt

Fix another ktlint style issue

---

assets/store_descriptions/en-US/strings.xml

Closes https://github.com/openhab/openhab-android/issues/3631

assets/store_descriptions/en-US/strings.xml: add fullstop at end of sentences

---

mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
mobile/src/test/java/org/openhab/habdroid/model/IconResourceTest.kt

See https://github.com/openhab/openhab-webui/pull/2534

Special handling for icon=none only for oh source

---

mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt

Translate material icon underscores into iconify style dashes

---

docs/USAGE.md

Better docs for Sitemap command item

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt
mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/layout/fragment_notificationlist.xml
mobile/src/main/res/layout/fragment_status.xml

This reduces the flicker while loading Sitemaps and the notification list.

Add skelton view while loading

---

mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt

When the reload is triggered via the pull-down, don't remove icons from the cache. Especially over myopenhab.org it takes some seconds until all icons have been loaded.

Keep icons in cache when refreshing Sitemap

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
mobile/src/main/java/org/openhab/habdroid/ui/DayDream.kt
mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/ItemClient.kt

Also add error handling.
Closes #3654

Deduplicate code for listening to Item changes

---

mobile/src/foss/java/org/openhab/habdroid/core/NotificationPoller.kt
mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
mobile/src/main/AndroidManifest.xml
mobile/src/main/java/org/openhab/habdroid/core/NotificationDismissedReceiver.kt
mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt

Update summary notification when notification is dismissed

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/layout/fragment_status.xml

See https://github.com/openhab/openhab-android/issues/3740#issuecomment-2225089147

Revert skeleton for Sitemaps for now

---

mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt

Support switch press & release

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

Enforce authentication when the tile only opens MainActivity, which cannot be displayed on a locked screen.

Enforce auth for some tiles in device controls

---

mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt

Reverts openhab/openhab-android#3743
Fixes #3759

Revert "Don't cache responses with 0 content length"

---

mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
mobile/src/main/res/layout/fragment_loading_skeleton.xml

This time the skeleton isn't shown alongside with temporary progress (e.g. server discovery).

Reintroduce loading skeleton for sitemaps

---

mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt

Fix base64 images in notifications

---

mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
mobile/src/main/res/layout/activity_chart.xml
mobile/src/main/res/layout/activity_image.xml
mobile/src/main/res/layout/fragment_loading_skeleton.xml
mobile/src/main/res/layout/fragment_notificationlist.xml
mobile/src/main/res/values-night/themes.xml
mobile/src/main/res/values-v23/themes.xml
mobile/src/main/res/values/attrs.xml
mobile/src/main/res/values/themes.xml

Similar to the statically created skeleton.

Improve skeleton colors

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt

Several Buttons can occupy the same position (row, col), having different visibility. Make sure that we pick and display the visible one.

Fix handling of multiple buttons with different visibility in the same spot

---

.github/workflows/build.yml
.github/workflows/deploy-apk.yml
gradle.properties

With default values (512 MB) the daemon OOMs when building the app.

Increase memory allocation of Gradle daemon

---

mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt

Correctly catch HttpException when retrieving item

---

mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Fix resolving color state lists from theme

---

mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/util/MjpegStreamer.kt

This broke in #3787
Fixes #3802

Fix MjpegVideoViewHolder instantiation

---

mobile/src/main/res/values/strings.xml

Rename the user-facing parts of the notification channels.

Notification channels: severity => tag

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt

Fix text items with newline character

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/ui/ColorItemActivity.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt
mobile/src/main/java/org/openhab/habdroid/util/ColorPickerHelper.kt
mobile/src/main/res/layout/activity_color_picker.xml
mobile/src/main/res/layout/bottom_sheet_color_picker.xml

Closes #3840
See https://github.com/QuadFlask/colorpicker/issues/136

Use forked color picker

---

mobile/src/main/java/org/openhab/habdroid/ui/DayDream.kt

Replace newline characters with `<br>` to keep the previous behavior.

Format screensaver item as html

---

mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

Fix foreground service type

---

mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt

See https://github.com/openhab/openhab-core/issues/4559

Disable controls for read-only items

---

mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt

Avoid doing view manipulation in background thread.
Fixes #3874

Fix crash during refresh in image viewer activity

---

mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationWorker.kt
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
mobile/src/main/java/org/openhab/habdroid/background/PeriodicItemUpdateWorker.kt

This can lead to ANRs, like the current myOH outage shows.

Avoid calling runBlocking from main thread

---

mobile/build.gradle
mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt

https://github.com/openhab/openhab-android/pull/3871

Bump workmanager and fix NPE

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt

Fix some crashes in chart activity

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt

Fix crash on rotating chart activity

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt

Ask persistence API for data including the full chart range

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt

Try to derive minimum chart grid line interval from number format

---

mobile/build.gradle

See https://github.com/openhab/openhab-android/pull/3901#issuecomment-2912544302

Use SOURCE_DATE_EPOCH for reproducable builds

---

mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
mobile/src/main/res/values-w600dp/dimens.xml
mobile/src/main/res/values/dimens.xml

Improve chart X axis label handling
