openhab/openhab-android

- mobile/src/main/res/values-fr/strings.xml
French translation for mobile app
> Add French translation

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Signed-off-by: Dan Cunningham dan@digitaldan.com (github: digitaldan)
> This add fullscreen support on android devices 4.4 and later

- mobile/src/main/res/values-fr/strings.xml
Added fullscreen & ringtones items
> Updated FR Translation

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Couldn't get to rebase in three hours, so created new branch and manually re-added the changes. See #71 for reference. #71 may be closed (DUP!)
> Enables processing for URIs like on NFC tag. openhab://?item=command

- mobile/src/main/java/org/openhab/habdroid/core/GcmIntentService.java
Shortens ringtone evaluation time and code.
> Fix ringtone evaluation

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Signed-off-by: Dan Cunningham dan@digitaldan.com
> Adds navigation for full screen mode

- build.gradle
- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/HABDroid.java
> MultiDex support

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
I hope this help some of refresh issues.
> Refresh improvment

- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
When image or chart is refreshed should has authorization.
> Refreshed images should have authorization.

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
- mobile/src/test/java/org/openhab/habdroid/model/OpenHABItemTest.java
Fixes #153 
Also update Android gradle plugin to version 1.5.0
> 153 color items state

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/core/ConnectivityChangeReceiver.java
- mobile/src/main/java/org/openhab/habdroid/core/GcmBroadcastReceiver.java
- mobile/src/main/java/org/openhab/habdroid/core/GcmIntentService.java
- mobile/src/main/java/org/openhab/habdroid/core/HABDroid.java
- mobile/src/main/java/org/openhab/habdroid/core/NotificationDeletedBroadcastReceiver.java
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABLinkedPage.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidgetDataSource.java
- mobile/src/main/java/org/openhab/habdroid/ui/AnchorWebViewClient.java
- mobile/src/main/java/org/openhab/habdroid/ui/BindingThingTypesFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABBindingFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryInboxFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABFragmentPagerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/drawer/OpenHABDrawerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/ColorPicker.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/ColorPickerDialog.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/java/org/openhab/habdroid/util/MjpegInputStream.java
- mobile/src/main/java/org/openhab/habdroid/util/MjpegStreamer.java
- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- wear/build.gradle
Fixes #171 
Also specify android wearable support version
This will also fix the "AAPT: No resource found that matches the given name" shown in https://openhab.ci.cloudbees.com/job/HABDroid/98/console
> Fix lint problems

- mobile/build.gradle
- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/ui/BindingThingTypesFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABBindingFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryInboxFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/layout-v21/activity_main_onepane.xml
- mobile/src/main/res/layout-v21/openhabwidgetlist_frameitem.xml
- mobile/src/main/res/layout/activity_main_onepane.xml
- mobile/src/main/res/layout/openhabwidgetlist_frameitem.xml
- mobile/src/main/res/values-v21/themes.xml
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/attrs.xml
- mobile/src/main/res/values/colors.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/values/themes.xml
- Implemented black/amoled theme
- Added material design hamburger Icon and animated it
- Updated to AppCompatActivity
- Auto formatted the files I touched
- fixed potential crash in null activity checks
- extracted hard-coded strings to xml
- replaced deprecated drawertoggle and pager APIs
**Gradle build updates**
- updated most gradle dependencies to be explicit version numbers to help with build time and eliminate possible bugs introduced by dependency version changes
- added a build config flag for indicating if the build "is developer" - this is less prone to being accidentally left true for production builds. Building debug variant automatically sets debug mode and building production disables it.
- updated compile version to the latest 23
- updated target version to 22. The latest …
> Implemented #170 - Support for black/amoled theme

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
- mobile/src/main/java/org/openhab/habdroid/ui/AnchorWebViewClient.java
Entering local url with port 84438 was causing unhandled IllegalArgumentException error in a background thread causing the app to vanish
> Entering invalid local url causes OpenHAB app to die #174

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABBindingFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryInboxFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/MjpegStreamer.java
- mobile/src/main/java/org/openhab/habdroid/util/MyAsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MySSLSocketFactory.java
> Upgrading to latest http-async library

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Fixes NPE when labels have no value

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
> Check for UNDEF type as well as NULL, fixes #185

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
> Ensures we can not crash if we do not have a float value

- mobile/src/main/java/org/openhab/habdroid/ui/BindingThingTypesFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABBindingFragment.java
> Fixes crash when clicking on bindindg entrey.  Fixes #189

- CONTRIBUTING.md
> Replace "mailing list" with "community forum"

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
> Fixes issue where volume buttons could crash app.

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
small style clean up for hard coded floats.
> small style clean up for hard coded floats.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
And sends to play store to get some.
Fixes #198
Signed-off-by: Brenda Wallace <brenda@wallace.net.nz>
> Catches error when no speech installed.

- mobile/src/main/java/org/openhab/habdroid/core/HABDroid.java
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABSitemap.java
- mobile/src/main/java/org/openhab/habdroid/model/thing/ThingType.java
- mobile/src/main/java/org/openhab/habdroid/ui/BindingThingTypesAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABBindingAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABDiscoveryInboxAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/drawer/OpenHABDrawerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
There's plenty of unused imports in the java. Removed using the power of android-studio, and re-tested.
> Removed unused imports

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
> Fixes #219

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Added Line:
```pagerAdapter.setOpenHABBaseUrl(openHABBaseUrl);```to openHABMainActivity
This set the openHABBaseUrl of pagerAdapter after a screen rotate if it was set before
This will Fix issue [#222]
> [#222] Fixed

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Fixes a NPE exception related to fix #219

- mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
> collapse a bunch of exception catchers

- mobile/src/main/AndroidManifest.xml
> Update release to 1.8.0.3

- mobile/src/main/java/org/openhab/habdroid/util/Util.java
> Check for null values when comparing sitemap labels, Fixes #236

- mobile/src/main/AndroidManifest.xml
> Bump to 1.8.0.4

- mobile/src/main/res/values-es/strings.xml
> Enhancement #151 Spanish translation

- KeyAuth.md
- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/java/org/openhab/habdroid/util/MyAsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MyKeyManager.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Support HTTPS with client certificate authentication

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABFragmentPagerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
> Updating to work with any openhab.org domain.

- mobile/src/main/res/values-ja/strings.xml
> Added Japanese translation

- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
Modified encoding of passwords. Loading of images failed if the password contains a line terminator.
Signed-off-by: Volker Daube <vd-github@online.de> (github: Snickermicker)
> Fix attempt at #116

- mobile/src/main/res/values-lt/strings.xml
BONUS: Lithuanian app description for play store
> Tai yra openHAB, atvirojo kodo išmaniųjų namų sistemos, Android programėlė. open Home Automation Bus (openHAB) projektas siekia pateikti universalią platformą, kuri apjungia visus visiems išmaniųjų namų įrenginius. Platforma siekia veikti su plačiu gamintojų ir įrenginių/protolų spektu. openHAB apjungia skirtingas duomenų perdavimo sistemas, įrenginius ir protokolus. Palaikomos technologijos: KNX, Modbus, DMX, Philips Hue, PLCBus, Sonos, Plugwise, IHC/Elko, RFXCOM, Homematic, Koubachi, Pulseaudio, Samsung TV, Bluetooth, One-Wire, Novelan, Asterisk, paprasti serial įrenginiai ir daugelis kitų. Palaikomos visos openHAB galimybės bei NFC žymomis paremta navigacija patalpose, automatinis jūsų openHAB serverio aptikimas ir nuotolinis …
> Add Lithuanian translation

- mobile/src/main/AndroidManifest.xml
> Bump version for next release

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/core/NetworkConnectivityInfo.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/res/layout/openhabinfo.xml
- mobile/src/main/res/layout/openhabwritetag.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
- wear/build.gradle
This reverts commit 7e405c5e20ae97fc924146038decea68a5b3c827. From PR #268
> Revert "Update to latest API+tools+gradle+misc. (#268)"

- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> make "icon format" in settings translatable

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/core/NetworkConnectivityInfo.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/res/layout/openhabinfo.xml
- mobile/src/main/res/layout/openhabwritetag.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
- wear/build.gradle
A re-do of #268 - Hope this works better.
> Update to latest API+tools+gradle+misc.  (try #2)

- build.gradle
> Updates gradle plugin to latest 2.4.0-alpha7

- mobile/src/main/res/values/strings.xml
> remove question mark as default value

- mobile/src/main/AndroidManifest.xml
> Update version number for release

- README.md
> change google play badge height

- mobile/src/main/AndroidManifest.xml
> updates version number for release

- README.md
When we have them, we can show them :)
> add screenshots to readme

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/MyAsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MyHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MySyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/test/java/org/openhab/habdroid/util/MySyncHttpClientTest.java
> Restore SSL Client Certificate Authentication feature

- mobile/build.gradle
> Updates SVG library to current master (using git commit hash) Fixes #338

- mobile/src/main/AndroidManifest.xml
> Bump to next version for release

- mobile/src/main/res/values-nl/strings.xml
I love Android Studio so much...
Signed-off-by: mueller-ma mueller-ma@users.noreply.github.com
> Remove empty string

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/res/drawable/splashscreen.xml
- mobile/src/main/res/layout/openhabstartup.xml
- mobile/src/main/res/values/themes.xml
This PR adds a screen with the openhab logo on startup.
> Add splash screen

- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Display correct icon for dimmer items controlled by a switch

- mobile/src/main/res/values-fr/strings.xml
> Fixed french translation

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
I have tested it by setting chartItem to null before it is checked if it's null and the app didn't crash. This is just a quick fix and we should have a look why chartitem is null.
Fix #396
> 396 chart crash

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/URLInputPreference.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/layout/activity_prefs.xml
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-ja/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-nl/strings.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
This started off as an improvement for the DE translation, but while working on the translation I found a number of improvement areas in the preference handling code, which I also fixed. I thought about adding them in a separate PR, but unfortunately they touch strings as well, so would conflict with the DE translation update.
If you prefer, I can split this PR to merge the translation updates first, then submit the preference code updates in a separate PR later.
> Preference UX improvements

- mobile/src/main/res/layout/openhabwidgetlist_icontext.xml
- mobile/src/main/res/layout/openhabwidgetlist_sectionswitchitem.xml
> Second try to fix #121 and #359

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/layout/openhabwidgetlist_sectionswitchitem_spinner.xml
> Selection: Add title and padding

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Make encoding check case insensitive

- README.md
I think we should write them down anywhere
> Add features to readme

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Support for image item

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Video: fix #402

- mobile/src/main/res/values-fr/strings.xml
> French translation adjusted to the recent changes

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Fix the label display for a selection item

- mobile/src/main/res/values-ru/strings.xml
Update translation after #337 was merged
> Update Russian translation

- mobile/src/main/res/values-lt/strings.xml
> Update Lithuanian translation

- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-ru/strings.xml
- mobile/src/main/res/values/strings.xml
These changes are suggested by Android Studio
> Minor changes to strings

- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Fix color switches and slider

- .travis.yml
- README.md
- build.gradle
- mobile/build.gradle
- mobile/src/main/res/values-el/strings.xml
> Add travis ci config file and ensure that builds pass

- mobile/src/main/AndroidManifest.xml
> Updating build to v2.0.0 and build 26

- mobile/src/main/res/layout/openhabwidgetlist_coloritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_icontext.xml
- mobile/src/main/res/layout/openhabwidgetlist_rollershutteritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_selectionitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_setpointitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_slideritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_switchitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_textitem.xml
This is the same than #390, but for all other elements.
I changed the relative layouts to constraint layouts.
Fixes #435
After:
Sitemap:
```
Selection item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahhhhh" mappings=[1="foo", 2="bar"]
Switch item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahh" mappings=[1="foo", 2="bar"]
Switch item=number4 label="hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddhhhhaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaahh"
Setpoint item=number4 …
```
> Fix overlapping label and item text/buttons

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Selection: value not in list

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/layout/openhabwidgetlist_simple_spinner_item.xml
> Right align spinner items

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
Per the discussion in #446 this reverts https://github.com/openhab/openhab.android/commit/058c3f9ad8238eacd3a021b63a023ab424ce6f0f
> Revert volume control buttons

- README.md
> Fix links to screenshots

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
It appears of if the step size is set to zero we would have a divide by zero.  This should resolve #468
> Ensure step size has a minimum of 1

- mobile/src/main/res/values-de/strings.xml
@maniac103 "Notification message" => "Benachrichtigung"?
> Update German translation

- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values/strings.xml
Restart oh and go to http://oh/rest/items to see this code.
> Add string for http code 503

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
> Chart: fix requested chart width in landscape mode

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-ru/strings.xml
- mobile/src/main/res/values/strings.xml
https://developer.android.com/reference/android/R.string.html#ok
> Use Android res for "ok" string

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
See https://stackoverflow.com/questions/5960678/whats-the-difference-between-commit-and-apply-in-shared-preference#5960732
> Use preferencesEditor.apply instead of .commit

- mobile/src/main/res/values-fr/strings.xml
> Updated French translation

- .travis.yml
> Fixing travis for full release

- .travis.yml
> Delete tage if exists

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
> Avoid useless refresh every 30 seconds

- .travis.yml
> Reverting automatic pushes for now

- mobile/src/main/AndroidManifest.xml
> bump version number

- README.md
> Add bountysource badge to readme

- .travis.yml
- mobile/src/test/java/org/openhab/habdroid/model/OpenHAB2WidgetTest.java
I have a few questions about my PR:
1. Should simple getter and setter be tested?
2. Should I create a test case for each object I create or is it better to have a seperate test case for each assertEquals?
3. Why does the test testWithObject2 not fail? I set different colors for label, icon and value, but the 3 getter return all 0.
4. Should I test for the IndexOutOfBoundsException in testWithObject2?
> Extend OpenHAB2WidgetTest

- docs/USAGE.md
> Change repo name

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
- mobile/src/main/res/values/strings.xml
> Use localized strings instead of hardcoded strings for NFC action list

- mobile/src/main/java/org/openhab/habdroid/ui/widget/URLInputPreference.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-el/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-ja/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-nl/strings.xml
- mobile/src/main/res/values-ru/strings.xml
- mobile/src/main/res/values/strings.xml
Fix #587 
@ThomDietrich Is this the correct way to change a string name?
> Fix typo in string name

- README.md
- mobile/src/main/res/values/strings.xml
Related to #342 
Related to #583 
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> Add crowdin localization details to README and strings.xml

- .pullapprove.yml
See https://github.com/openhab/openhab-android/pull/593#issuecomment-354740254
> Use github teams instead of a list of users

- mobile/src/main/res/values/strings.xml
> Correct GCM string

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/res/layout/openhabinfo.xml
> A little bit of redesign for openHAB-Information on About screen

- mobile/src/main/res/xml/preferences.xml
> Show translated icon format instead of the value

- docs/USAGE.md
Thanks to @bgilmer77 https://github.com/openhab/openhab-docs/pull/587
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> USAGE: Add correct cloud notifications link

- mobile/src/main/res/values/strings.xml
* Change "phone" to "device"
* Remove redundant "setting" from settings menu strings
@ThomDietrich @maniac103
> Improve english strings

- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/IntroActivityTest.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.java
> Remove things sitemap from side menu and sitemap selection

- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
This message isn't really an error and its pretty spammy in the logfiles.
> Change log message to type debug

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
> Show back, not hamburger for notification fragment

- mobile/src/main/res/layout/openhababout.xml
- mobile/src/main/res/layout/openhabwidgetlist_coloritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_rollershutteritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_setpointitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_videomjpegitem.xml
- mobile/src/main/res/layout/voice_widget.xml
- mobile/src/main/res/values/strings.xml
@cribskip Please add content descriptions to the voice widget in #545
> Add content description to pictures without

- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
> Enable multidex on Andoid versions prior to 21

- crowdin.yml
> Add /assets/store_descriptions/ to crowdin

- assets/store_descriptions/en-US/strings.sh
- assets/store_descriptions/generate_and_validate.sh
- fastlane/metadata/android/en-US/full_description.txt
* Use https for all links 
* Prohibit pipe and semicolon in descriptions 
@kubawolanin @Confectrician You will have to resubmit your translation after this is merged.
> Use pipe instead of slash in sed command

- .stickler.yml
- checkstyle.xml
Fixes #598
Repo needs to be enabled on https://stickler-ci.com/
> Add checkstyle and stickler ci config

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
> Fix sitemap label not showing up in preferences

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
> NFC: Treat group switches like normal switches

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/drawer/OpenHABDrawerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
> Fix flickering icons on sitemap reload.

- .travis.yml
> Deploy foss build on github

- .travis.yml
> Use more user friendly names for github deployed apks

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/values/attrs.xml
> Fix resolving of chart theme attribute.

- mobile/src/main/java/org/openhab/habdroid/util/Util.java
Fixes #710
I changed all activities to inherit from baseAcitivity instead of AppCompatActivity, except IntroActivity. Doesn't care, since the theme cannot be changed before going throught the intro.
> Change title bar color in "last apps" to themed color

- mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.java
Get rid of the stactraces, when the font is not found.
Fixes #697
> Simplify intro code and change font

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/java/org/openhab/habdroid/util/MyHttpClient.java
They are all small changes, so I put them in one PR instead of having 12.
> Fix some lint errors

- mobile/src/main/res/values/strings.xml
> Include intro libary strings for easy translation

- mobile/src/full/java/org/openhab/habdroid/core/GcmIntentService.java
> Play no ringtone if set to mute

- build.gradle
- mobile/build.gradle
@digitaldan Can you check if it still works as expected in the full build?
> Remove crash reporting from foss build

- mobile/src/main/res/layout/openhabwidgetlist_rollershutteritem.xml
> Fix rollershutter height

- mobile/src/main/AndroidManifest.xml
Both entries were added to the manifest, but no code was added to
support these features.
See #724
As this PR doesn't really fix the issue, I'll wait for a real fix and only merge this PR, if the bug isn't fixed until the next release.
> Fix split screen mode

- mobile/src/main/res/values/analytics.xml
> Remove analytics config

- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
The old check only worked for icons, but not for image items, since they
don't include "format=SVG" in their URL.
I think I have seen an issue for that, but I cannot find it anymore :(
> Fix SVG image items

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/drawable/ic_spinner_caret_black.xml
- mobile/src/main/res/drawable/ic_spinner_caret_white.xml
- mobile/src/main/res/layout/openhabwidgetlist_setpointitem.xml
- mobile/src/main/res/values/attrs.xml
- mobile/src/main/res/values/themes.xml
* Change arrow color to white (taken from
https://github.com/maniac103/openhab.android/commit/b824cd31253aaa813fa6ee7f98b5c99107be128d)
* Change arrow width to match selection items
> Improve setpoint look

- mobile/build.gradle
> Remove unused dependencies

- .travis.yml
- mobile/build.gradle
- mobile/src/beta/res/values/strings.xml
- travis/build-and-test-apk.sh
- travis/commit-version-and-metadata.sh
Fixes #765
Need to resolve #704 in this PR, too.
> WIP: Add beta suffix to package name

- .travis.yml
- travis/build-and-test-apk.sh
> Fix deploy

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidget.java
We shall not convert the 'OFF' state to an 'ON' path.
Fixes #781
> Fix fetching switch icons.

- mobile/src/androidTest/java/org/openhab/habdroid/ui/WidgetAdapterTest.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidget.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/attrs.xml
- mobile/src/main/res/values/themes.xml
- mobile/src/test/java/org/openhab/habdroid/model/OpenHABWidgetTest.java
Fixes #637
Before:
After:
I'm not sure about both blue and maroon in dark themes. They could be a bit brighter. WDYT?
> Change value colors according to theme background

- fastlane/Screengrabfile
> Only run screengrab in en-US for now

- .travis.yml
- fastlane/Screengrabfile
- mobile/src/androidTest/java/org/openhab/habdroid/screengrab/ScreengrabTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/NfcTest.java
- travis/prepare-deploy.sh
> Pass NFC test on all locales

- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
Instead of having a fixed timer scheduling a handler and a boolean
suppressing timer events during reload, do all scheduling using the
handler.
> Simplify image view refresh logic.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
PR #775 introduced code that should have been adapted to the
refactorings done in #781, but that went unnoticed.
> Fix merge conflict introduced with #775/#781

- assets/store_descriptions/en-US/strings.sh
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> Correct typo in store descriptions

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.java
but let the default sitemap always be the first one.
Fixes #270
> Sort sitemaps alphabetically

- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/ssl_preferences.xml
> Show ssl client howto hint again

- assets/store_descriptions/en-US/strings.xml
- assets/store_descriptions/generate_and_validate.py
- fastlane/metadata/android/en-US/full_description.txt
Tested in my bot repo: https://github.com/mueller-ma-bot/openhab.android/pull/14/files
> Improve Python script

- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
> Bypass cache when refreshing image items.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
> Include back stack in prefs back arrow navigation.

- mobile/src/main/res/values/strings.xml
See https://community.openhab.org/t/android-app-2-1-0-notification-sound/43976/9
> s/Ring tone/Notification sound

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/util/SyncHttpClient.java
> Fix voice interpreter API URL.

- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
As mentioned in https://github.com/openhab/openhab-android/pull/861#issuecomment-384981343
> Fix handling of URL query parameters.

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
This service runs in a background thread now, so UI updates need to be
explicitly scheduled in the main thread.
Closes #866
> Fix voice service toast generation.

- assets/store_descriptions/en-US/strings.xml
- docs/USAGE.md
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
Update documentation links to the new website layout.
Should I also update the links in the fastlane and assets directories or should that be done via Crowdin?
> Update documentation links

- mobile/src/full/res/values/strings.xml
- mobile/src/main/res/values/strings.xml
> Use contraced words in English strings

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/drawable/ic_keyboard_arrow_right_black_24dp.xml
- mobile/src/main/res/drawable/ic_keyboard_arrow_right_white_24dp.xml
- mobile/src/main/res/layout/openhabwidgetlist_groupitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_textitem.xml
- mobile/src/main/res/values/attrs.xml
- mobile/src/main/res/values/themes.xml
> Add arrow to widget when clicking opens a sub page

- travis/bump-versioncode.sh
> Fix "-release-fdroid" tags

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
> Show sitemap selection dialog after clearing it in the settings

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
> Add support for relative urls in webview

- mobile/src/full/AndroidManifest.xml
- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Add vibration and led light to notifications

- build.gradle
- mobile/build.gradle
Error message from Travis:
````
Could not resolve all files for configuration ':mobile:fullBetaReleaseCompileClasspath'.
> Could not find firebase-core.jar (com.google.firebase:firebase-core:12.0.1).
Searched in the following locations:
https://jcenter.bintray.com/com/google/firebase/firebase-core/12.0.1/firebase-core-12.0.1.jar
> Could not find common.jar (android.arch.core:common:1.1.0).
Searched in the following locations:
https://jcenter.bintray.com/android/arch/core/common/1.1.0/common-1.1.0.jar
````
> Try to fix failing travis

- KeyAuth.md
- mobile/src/main/res/values/strings.xml
> Change link to key auth how-to

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/res/values/strings.xml
> Don't show "Could not discover" message when on mobile data

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/network_security_config.xml
> Use networkSecurityConfig to disallow http to myopenhab.org

- assets/store_descriptions/en-US/strings.xml
> Fix fastlane description

- mobile/src/main/res/values/strings.xml
Google removed the "Writing" page from material.io when they redesigned it. I don't know if it's still official or not: https://web.archive.org/web/20180103183733/https://material.io/guidelines/style/writing.html#writing-capitalization-punctuation
> Add fullstop when having more than one sentence

- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidget.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/SyncHttpClient.java
- mobile/src/test/java/org/openhab/habdroid/core/connection/DefaultConnectionTest.java
- Use smaller timeouts for notification icons to avoid timeouts if server is set to 'notifications only'
- Don't attempt to fetch 'none' icon
> Some fixes for icon loading

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Never show password in cleartext

- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/test/java/org/openhab/habdroid/core/connection/DefaultConnectionTest.java
> Change user agent to "openHAB client for Android"

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java
- Correctly refresh images after pull-to-refresh
- Correctly resume image refresh when reusing views
Fixes #985
> Fix image refresh regressions

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
> Use Toasty library for Toasts

- .cirrus.yml
- .travis.yml
> Add Cirrus CI

- assets/store_descriptions/en-US/strings.xml
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
> Change link to privacy policy

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/test/java/org/openhab/habdroid/ui/OpenHABPreferencesActivityTest.java
Fixes https://console.firebase.google.com/project/openhab-mobile/crashlytics/app/android:org.openhab.habdroid/issues/5bab56f2f8b88c29635b445a
> Make beautifyUrl() null safe

- .stickler.yml
> Run Checkstyle with Stickler CI

- assets/store_descriptions/generate_and_validate.py
> Catch specific error in Python script

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.java
> Remove hashCode() from AbstractConnection

- travis/uploads.sh
> Retry download of changelog

- .cirrus.yml
- assets/store_descriptions/generate_and_validate.py
- travis/validate-app-strings.py
> Move app string validation to separate file

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/MaxHeightWebView.java
- mobile/src/main/res/layout/widgetlist_webitem.xml
See https://github.com/openhab/openhab-android/issues/981 and https://github.com/eclipse/smarthome/issues/6077
> Treat "height" parameter in webview as max height

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/res/layout/select_dialog_singlechoice.xml
IMO the font was always too large in the dialog.
Old:
New:
> Decrease font size in selection widget dialog

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
Fixes #1018
@maniac103 Do you want to review this?
> Start image refresh after phone comes back from sleep

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
> Fix crash when resetting default sitemap and no connection is available

- mobile/src/main/res/drawable/ic_keyboard_arrow_right_black_24dp.xml
- mobile/src/main/res/drawable/ic_keyboard_arrow_right_white_24dp.xml
- mobile/src/main/res/layout/widgetlist_frameitem.xml
- mobile/src/main/res/layout/widgetlist_iconsmallvaluetext.xml
- mobile/src/main/res/layout/widgetlist_icontext.xml
- mobile/src/main/res/layout/widgetlist_iconvaluetext.xml
- mobile/src/main/res/layout/widgetlist_webitem.xml
Fixes #1076
@gargamelonly Can you test the apk [mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/2550015/mobile-foss-beta-debug.zip)?
> Fix RTL issues with item labels and icons

- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Use switches to:
>  * Toggle a single option on or off, on mobile and tablet
>  * Immediately activate or deactivate something
from https://material.io/design/components/selection-controls.html#usage
> Use switches instead of checkboxes in settings

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
> Fix back arrow behavior in about

- README.md
> Add Dependabot badge to Readme

- travis/test.sh
> Retry UI tests if they fail

- mobile/build.gradle
> Replace compile with implementation in build.gradle

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
> Remove getString() from Toasty call

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
> Show URL settings hint when URL is not set

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
> Add logging for SSE events

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.java
> [Bugfix] Fix lgtm alerts

- travis/test.sh
> Make sure Travis jobs fail if build fails

- mobile/build.gradle
> Bump powermock-* to 2.0.0

- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.java
- mobile/src/main/java/org/openhab/habdroid/ui/AnchorWebViewClient.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/res/drawable/ic_view_module_black_24dp.xml
- mobile/src/main/res/layout/fragment_habpanel.xml
- mobile/src/main/res/menu/left_drawer.xml
- mobile/src/main/res/values/strings.xml
> Display HABPanel

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java
> Fix section switch button handling

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/res/xml/network_security_config.xml
> Add networkSecurityConfig to allow user added CAs

- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/layout/notificationlist_item.xml
- mobile/src/main/res/layout/widgetlist_icontext.xml
- mobile/src/main/res/values/dimens.xml
Fixes #728
@maniac103 I copied and modified your code from OctoDroid. How do I need to mention you or OctoDroid in the comments to avoid copyright violations?
> Scale svg correctly

- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.java
> Fix crash with MapView if item has no state

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/UrlInputPreference.java
- mobile/src/main/res/values/strings.xml
See https://github.com/openhab/openhab-android/issues/1184
> Show hints if using wrong protocol to wrong ports

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
> Fix possible NPE

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Show shortcut to notification settings for Oreo and above

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
> Fix selection of HABPanel panel

- CONTRIBUTING.md
Added FAQ with questions I was asking myself, when I first opened the project in Android Studio.
Signed-off-by: Johannes Ptaszyk <johannes@ptaszyk.de>
> Add FAQ chapter to CONTRIBUTING.md

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
> Fix NPE in colorpicker

- README.md
see #1223
Signed-off-by: Jochen Bauer <jochen.bauer@gmail.com> (github: Jochen1980)
> Fixed readme bug 1223

- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
> Don't play notification sound for summary notification.

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
> Add authentication header to SSE events

- mobile/google-services.json
- travis/prepare-deploy.sh
> Fix fullBeta build

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
> Fix HABPanel HTTP Error 401

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.java
> Fix NPE in LogActivity

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.java
> Improve WebView fragment

- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
Matches what BasicUI is doing.
Closes #1248
> Include item value in page title.

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/res/values/strings.xml
> Add "Turn off" action to demo mode snackbar

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.java
> Rename HabDroidApplication.java to OpenHabApplication.java

- mobile/src/main/res/layout/widgetlist_slideritem.xml
- mobile/src/main/res/values-w600dp/dimens.xml
- mobile/src/main/res/values-w750dp/dimens.xml
- mobile/src/main/res/values/dimens.xml
> Change slider size according to screen size

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
See https://community.openhab.org/t/setpoint-cant-edit-the-value-with-fractional-digit/70705
> Improve number handling

- mobile/src/main/java/org/openhab/habdroid/util/Util.java
> Assign correct colors to swipe refresh layouts

- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.java
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.openhab.habdroid.model.Item.members()' on a null object reference
at org.openhab.habdroid.ui.MapViewHelper$GoogleMapsViewHolder.applyPositionAndLabel(MapViewHelper.java:148)
at org.openhab.habdroid.ui.MapViewHelper$GoogleMapsViewHolder.lambda$new$2(MapViewHelper.java:56)
````
> Fix NPE in MapView

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/res/layout/widgetlist_setpointitem.xml
- mobile/src/main/res/values/strings.xml
Edit: This adds a setting that allows switching between the old (with up/down
buttons) and new (with dialog) setpoint widgets.
> Add up/down buttons to setpoint widgets

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
> Support writing NFC tags of Setpoint and Slider

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.java
> Migrate WorkManager to AndroidX

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Add labels to issue templates

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/values/strings.xml
Show an error message to the user instead of retrying.
Fixes #741
Closes #812
> Report error during load of sitemap back to user

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/res/values/strings.xml
> Fix ActivityNotFoundException in About

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Bump Gradle

- mobile/src/main/java/org/openhab/habdroid/model/Widget.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
Closes #90
Closes #550
Closes #735 
> Create "row click" shortcuts for a few widgets

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/res/drawable/ic_network_strength_off_outline_black_24dp.xml
- mobile/src/main/res/drawable/ic_signal_cellular_off_black_24dp.xml
- mobile/src/main/res/layout/fragment_status.xml
* Add retry button. Fixes #1309
* Use outline icon. Fixes #1310
> Improve MissingConfigurationFragment

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
> Remove unused Handler in PreferencesActivity

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/VoiceWidget.java
- mobile/src/main/res/values/strings.xml
* Hide voice widgets
* Always show mic in action bar, but open snackbar with link to Google's
stt app if no stt app is installed
Fixes #1323
> Improve UX if no speech to text app is installed

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.java
Don't fail on a timeout instantly, but increase the retry count.
> Improve connection check reachablility

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/res/values/strings.xml
> Fetch about screen information async

- README.md
> Use screenshots from docs in Readme

- stickler/checkstyle.xml
> Disable Stickler failure if JavaDoc is missing

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/res/values/strings.xml
> Remove duplicate String resource

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.java
Longitude can be in a -180..180° range.
> Fix location parsing sanity check.

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
> Fix crash in SectionSwitchViewHolder#handleRowClick()

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/SyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/values/strings.xml
> Add ability to create sitemap shortcuts

- README.md
- assets/store_descriptions/en-US/strings.xml
- mobile/build.gradle
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.java
- mobile/src/foss/res/drawable/ic_location_on_red_24dp.xml
- mobile/src/foss/res/layout/openhabwidgetlist_mapitem.xml
> Support MapView in foss flavor

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.java
> Use Util.convertDpToPixel() in OsmViewHolder

- docs/USAGE.md
> Add notification troubleshooting section to docs

- assets/store_descriptions/en-US/strings.xml
- assets/store_descriptions/generate_and_validate.py
* Anti feature has been removed in F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/4704
* The "empty point" causes a lot of issues with translating it.
> Update App Store description

- assets/store_descriptions/generate_and_validate.py
> Python: Remove redundant parentheses

- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
> Use UTF-8 for basic authentication password

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
> Don't allow scrolling OSM if position is null

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
> Correctly initialize notification drawer entries after device rotation.

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Don't open sitemap after pinning to home

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Don't show item update animation

- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/res/layout/widgetlist_invisibleitem.xml
Track visibility changes via SSE events, and add a fallback for older
servers which triggers a page reload if an unknown widget becomes
visible.
Fixes #1094
> Add proper handling for invisible widgets.

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
> Improve fragment navigation logic

- mobile/build.gradle
Trying to find the reason of https://github.com/openhab/openhab-android/pull/1356#issuecomment-504578583
> Show exception stacktraces occurring during test.

- mobile/src/main/res/layout/activity_log.xml
> Make log selectable

- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
* Don't suggest commands for Charts
* Suggest current value for Numbers and Strings
> Improve command suggestions

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
The first retry is now after 10 seconds, the second one after 20, ...
Fixes #1370
> Retry background item updates more often

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
> Handle row click for MapView items

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/res/values/strings.xml
> Require pressing back twice to exit app in fullscreen

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
> Fix typo in content controller instance state key.

- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
> Catch IOException when attempting FCM registration.

- docs/USAGE.md
> Add voice command rule to docs

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
> Fix nullability of KeyManager callbacks.

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
> Fix widget visibility tracking algorithm

- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
> Defer sitemap selection until onStart() and refactor pending action handling

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
See https://github.com/openhab/openhab-android/pull/1440#discussion_r301690665
> Help Kotlin compiler in detecting tail recursion.

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
> Catch NPE in OSM library

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
> Close HABPanel if sitemap shortcut is used

- mobile/src/androidTest/java/org/openhab/habdroid/ui/PreferencesActivityTest.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
> Fix host formatting in prefs

- mobile/src/main/java/org/openhab/habdroid/core/OnUpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Previous if the app got stopped during the intro, the intro won't be
shown again on next start.
> Make sure that intro is shown again if app is stopped

- assets/store_descriptions/en-US/strings.xml
- assets/store_descriptions/generate_and_validate.py
> Make Play Store description compliant

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
> Show MapView dialog in fullscreen

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
See
https://community.openhab.org/t/slider-items-with-new-android-app-2-8-0-not-working-anymore/79344/5
> Use format specifier also when updating non-UoM items.

- mobile/build.gradle
Dependabot will open only one PR, e.g. https://github.com/openhab/openhab-android/pull/1479
> Use gradle variables for lib versions if two or more have the same version

- .idea/codeStyles/Project.xml
- .idea/dictionaries/openhab.xml
- .idea/misc.xml
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
> Update to Android Studio 3.5

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
- mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/test/java/org/openhab/habdroid/model/SitemapTest.kt
> Fix build warnings

- .idea/misc.xml
- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
and bump build tools version.
See #1295
> Use settings panel to enable wifi on Android Q

- mobile/src/androidTest/java/org/openhab/habdroid/ui/NfcTest.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/ContextMenuAwareRecyclerView.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
- mobile/src/main/java/org/openhab/habdroid/util/Util.kt
- mobile/src/main/res/layout/fragment_widgetlist.xml
- mobile/src/main/res/values/strings.xml
* Show a menu with the possible actions: write item update tag, write
sitemap tag or create shortcut
* Show "custom" state for item update tags
> Improve long press menu

- docs/USAGE.md
> Remove excessive new line from docs

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/foss/res/values/strings.xml
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Offer opening MapViews in Browser or native Maps app

- mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt
- mobile/src/main/res/xml/local_connection_preferences.xml
- mobile/src/main/res/xml/remote_connection_preferences.xml
* Change input type from text to url
* Remove whitespaces before saving instead of showing an error
* Make sure ok button is disabled if invalid url is entered
> Improve UrlInputPreference

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/Util.kt
- mobile/src/main/res/drawable/ic_error_outline_white_24dp.xml
- mobile/src/main/res/drawable/ic_error_white_24dp.xml
- mobile/src/main/res/drawable/ic_refresh_white_24dp.xml
- mobile/src/main/res/layout/activity_log.xml
- mobile/src/main/res/menu/log_menu.xml
- mobile/src/main/res/values/strings.xml
> Improve LogActivity

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/drawable/ic_halloween_orange_24dp.xml
> Improve slider thumb

- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/core/VoiceService.kt
- mobile/src/main/java/org/openhab/habdroid/util/Util.kt
> Show Toast if FCM registration fails

- .gitignore
- .idea/misc.xml
This file includes the name of the local JDK, which can be different on different installations.
> Ignore .idea/misc.xml

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerOnePane.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerTwoPane.kt
> Replace deprecated FragmentManager function

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Close context menu if connection is lost

- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
> Allow writing empty states on NFC tags

- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
Also listen for NFC adapter state changes.
See #1295
> Use Settings Panel to enable NFC in WriteTagActivity

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
> Call super func where needed

- .stickler.yml
> Fix ktlint issues automatically

- assets/store_descriptions/en-US/strings.xml
> Add Play Store Beta changelog

- mobile/src/main/res/layout/fragment_writenfc.xml
- mobile/src/main/res/values/strings.xml
> Center WriteTagActivity hints

- mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt
- mobile/src/main/res/values/strings.xml
> Fix crash if no ssl client certificate chooser is present

- docs/USAGE.md
> Advanced example of AlarmClock rule usage

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
Tasker mis-uses this api, so we ignore alarm clocks set by Tasker.
Closes #1341
> Ignore alarm clocks set by Tasker

- docs/USAGE.md
Closes https://github.com/openhab/openhab-docs/issues/666
> Explain how to speed up chart rendering

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
> Prune work when disabling item update pref

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
> Hide version and icon in used libs

- mobile/build.gradle
Update to latest version in 3.12.x series, as we don't want to bump min
required SDK version at this point.
> Update OkHttp to latest version.

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
> Fix HTTP response body leaks.

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/NfcInfo.kt
- mobile/src/main/java/org/openhab/habdroid/ui/NfcInfoActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/Constants.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/main/res/drawable/ic_nfc_black_120dp.xml
- mobile/src/main/res/drawable/ic_nfc_black_24dp.xml
- mobile/src/main/res/menu/left_drawer.xml
- mobile/src/main/res/values/strings.xml
>  Add NFC info and item select activity 

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
> Hide NFC drawer entry if no connection

- CONTRIBUTING.md
> Mention ktlint in CONTRIBUTING.md

- mobile/src/main/res/values/strings.xml
> Update in-app license version to EPL-2.0

- .idea/codeStyles/Project.xml
- .idea/encodings.xml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Bump gradle wrapper

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
> Fix crash if image couldn't be rendered

- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
As discussed in https://github.com/eclipse/smarthome/pull/4638, particularly https://github.com/eclipse/smarthome/pull/4638#issuecomment-347509218
> Implement TOGGLE command client-side only.

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
> Item picker: Close search view on back press

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
> Reschedule item uploads if prefix changes

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/res/values/strings.xml
and pass the mapped state around in preparation for #1582.
Fixes #1576
> Show label in background tasks error notifications

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
> Show prefix in summary

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
> Restore "errors only" state after device rotation

- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/res/layout/activity_writetag.xml
> Fix lock screen crash in WriteTagActivity

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/res/values/strings.xml
> Catch SecurityException if ringtone is on external storage

- mobile/build.gradle
> Bump "androidx.recyclerview:recyclerview"

- mobile/src/main/res/values-night/colors.xml
- mobile/src/main/res/values/colors.xml
- mobile/src/main/res/values/themes.xml
> Grey dark theme: Increase contrast between buttons and background

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
> Work around appcompat forcing font scale to 1.0

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
> Fix connection summary always set to insecure

- mobile/src/main/java/org/openhab/habdroid/ui/IntroActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
See https://github.com/openhab/openhab-android/issues/1651#issuecomment-548958146
> Increase logging in IntroActivity

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Font scaling should work not only in MainActivity, but in all of them.
> Move font scaling workaround to base class.

- README.md
> Readme: Add link to the documentation

- .github/ISSUE_TEMPLATE/bug-report.md
See https://github.com/openhab/openhab-android/issues/1651#issuecomment-548958146
> Update issue template

- .github/labeler.yml
- .github/workflows/build.yml
- .github/workflows/label.yml
- .github/workflows/validate-strings.yml
- Auto label PRs depending on the changed files (only for documentation, automation and localization)
- Build apk and run unit tests for (foss|full)x(beta|stable)
- Validate app store descriptions
> Add GitHub Actions config

- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
- mobile/src/main/java/org/openhab/habdroid/util/CustomBackupAgent.kt
> Make variable TAG private

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/res/menu/left_drawer.xml
- mobile/src/main/res/values/strings.xml
> Deduplicate string in Drawer

- docs/USAGE.md
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/TaskerPlugin.java
- mobile/src/main/res/values/strings.xml
> Support Tasker error reporting

- mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
> Handle new `anyFormat` parameter

- mobile/src/androidTest/java/org/openhab/habdroid/ui/NfcTest.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/res/values/strings.xml
> Create home screen widget via long press menu

- mobile/build.gradle
> Bump material from 1.1.0-beta01 to 1.1.0-beta02

- .github/labeler.yml
- .github/workflows/labeler.yml
> Add periodic labeler action

- mobile/build.gradle
This is a custom build of the library. Latest master + bumped
recyclerview.
There's a pending PR for this in the lib repo: https://github.com/mikepenz/AboutLibraries/pull/454
Fixes #1635
> Next try to fix AccessibilityNodeInfo StackOverflowError

- crowdin.yml
> Sign-off Crowdin commits

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
This one doesn't require us to use random git revisions.
Tested only lightly so far.
> Switch to OkHttp-internal SSE implementation.

- mobile/src/beta/res/values/strings.xml
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/stable/res/values/strings.xml
> Include "Beta" in Tasker plugin

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
- mobile/src/main/res/layout/activity_item_picker.xml
- mobile/src/main/res/layout/tasker_item_picker_config.xml
- mobile/src/main/res/values/strings.xml
> Choose between item commands and item updates in Tasker plugin

- mobile/src/main/java/org/openhab/habdroid/ui/NfcInfoActivity.kt
> Don't force NFC item picker into non-fullscreen

- mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/layout/activity_item_picker.xml
- mobile/src/main/res/layout/widget_item_picker_config.xml
- mobile/src/main/res/values/strings.xml
> Make widget label configurable

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/NfcItemPickerActivity.kt
- mobile/src/main/res/layout/nfc_item_picker_config.xml
> Show hint in nfc item picker

- mobile/src/main/res/values/arrays.xml
> Add pink and gold as supported colors

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
> Item Picker: Wait for connection

- mobile/src/main/res/layout/tasker_item_picker_config.xml
> Center Tasker item picker config

- mobile/src/main/res/layout/widget_item_update.xml
- mobile/src/main/res/layout/widget_item_update_small.xml
> Increase size of widget edit button

- mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
> Update icon if widget is edited

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
> Refresh Image and Chart items after resuming the app

- mobile/build.gradle
> Use upstream AboutLibraries again

- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
See https://github.com/openhab/openhab-android/issues/1651#issuecomment-548958146
> Enhance FCM registration error toast

- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
> Catch all exceptions thrown by androidsvg

- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/core/VoiceService.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
> Show openHAB icon in all toasts

- mobile/src/main/res/values/strings.xml
> Add comments to strings with multiple substitutions

- mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
This commit uses the certificate configured for the openhab server in webview widgets as well.
Ideally the user should be able to choose another certificate if needed, but I this fixes the case where the webview URL is behind the same reverse proxy as the openhab server and the certificate needed is the same.
Signed-off-by: rca <raphael.catolino@gmail.com>
> Do SSL Client auth in webview using the certificate configured for the

- mobile/src/main/res/values/strings.xml
See https://github.com/openhab/openhab-android/pull/1757#pullrequestreview-338552494
> Use xliff tags for strings

- mobile/src/main/res/values/strings.xml
Reverts openhab/openhab-android#1759
> Revert "Use xliff tags for strings"

- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
- mobile/src/main/res/values/strings.xml
> Support TOGGLE for Contact items

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Correctly show hint if subpage contains no visible widgets

- mobile/build.gradle
- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.kt
- mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/test/java/org/openhab/habdroid/model/SitemapTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
> Use anyFormat for all icons

- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
> Fix error message for SSL errors

- mobile/build.gradle
> Bump material from 1.1.0-beta02 to 1.1-0-rc02

- mobile/src/foss/java/org/openhab/habdroid/util/RemoteLog.kt
- mobile/src/full/java/org/openhab/habdroid/util/RemoteLog.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
This can help to trace down some crashes.
> Log to Crashlytics

- .idea/kotlinCodeInsightSettings.xml
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Add ability to create shortcut with dark background

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/foss/res/layout/widgetlist_mapitem.xml
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/res/layout/widgetlist_mapitem.xml
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/drawable/ic_location_off_grey_120dp.xml
- mobile/src/main/res/drawable/ic_location_off_grey_64dp.xml
- mobile/src/main/res/layout/widgetlist_mapitem_no_position.xml
- mobile/src/main/res/values/strings.xml
> Show hint in MapView if no location is set

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
> Close dialogs when opening a new page

- .github/workflows/build.yml
- mobile/build.gradle
- mobile/src/foss/java/org/openhab/habdroid/util/RemoteLog.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
> CI: Fail on Kotlin warning

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
> Don't set Sitemap from demo mode as default

- mobile/build.gradle
> Bump material components to 1.1.0

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Automatically retry after 30 seconds if there's no connection or
connection error.
See https://github.com/openhab/openhab-android/issues/1767#issuecomment-576285773
> Auto retry after connection failed

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/drawable/ic_access_time_white_24dp.xml
- mobile/src/main/res/layout/activity_about.xml
- mobile/src/main/res/layout/activity_chart.xml
- mobile/src/main/res/layout/activity_item_picker.xml
- mobile/src/main/res/layout/activity_log.xml
- mobile/src/main/res/layout/activity_main.xml
- mobile/src/main/res/layout/activity_prefs.xml
- mobile/src/main/res/layout/activity_writetag.xml
- mobile/src/main/res/menu/chart_menu.xml
- mobile/src/main/res/values/strings.xml
> Add fullscreen activity for charts

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
Fixes #1800
Tested with two Android 7 devices.
> Support bluetooth tethering

- README.md
> Add GitHub Actions badge to Readme

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
> Use requireContext() instead of context!!

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/Util.kt
- mobile/src/main/res/drawable/ic_star_border_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
But only for the stable release. The play store is not the recommended way to report issues with the beta version.
> Add 'rate app' to about menu

- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
> Restore webview state after rotation

- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
> Preserve authentication information over HTTP redirects.

- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/res/menu/chart_menu.xml
> Implement auto refresh in ChartActivity
