- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/VoiceWidget.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/java/org/openhab/habdroid/util/ContinuingIntentService.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values/strings.xml
This pull request fixes the following issues mentioned in #5 :
- HABdroid is not opened anymore when the microphone widget is used
- Text overlay (Toast) is displayed with the recognized command
- Voice recognition works regardless of whether HABdroid is active on the background or not
It does not address the following suggestions (maybe a seperate ticket can be created for these):
- Do not include two on-click functions (execute voice recognition & openHAB) in the widget
- Enable widget for lock screen
A few words about the implementation:
Previously, the voice command functionality was included in the OpenHABMainActivity, which was called by an Intent. That's probably why the HABdroid GUI was always opened, when the voice widget was used. I couldn't find a way to execute voice …
> Refactoring of microphone widget from activity into own service

- mobile/src/main/AndroidManifest.xml
This pull request should fix #33 . I cannot test it because I don't have a device without GPS.
Problem is that HABDroid uses permission ACCESS_FINE_LOCATION. This implies (see http://developer.android.com/guide/topics/manifest/uses-feature-element.html#permissions) that the android.hardware.location.gps feature is required to run HABDroid. As this is not the case, this feature should be marked as required false.
@belovictor: For which feature of HABDroid is ACCESS_FINE_LOCATION necessary? If it is not necessary, it would make more sense to remove this permission request. Let me know then I could update the pull request.
> Indicate that HABDroid also works on devices without GPS

- mobile/build.gradle
Encountered a problem similar to http://stackoverflow.com/questions/21645961/android-studio-processdebugresources-failed. Fixed by upgrading to the latest version of build tools for 21
> Fixed a build error Android Studio on Windows

- mobile/src/main/java/org/openhab/habdroid/ui/AnchorWebViewClient.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
Currently when speficying an openHAB WebView sitemap element pointing to
www.url.com/site.html#bottom the anchor (#bottom) is ignored.
Note: This PR might now be necessary. Currently the #anchor (aka
fragment) is not send by openHAB core. This should be fixed by
https://github.com/openhab/openhab/pull/2623
Once that PR is accepted, test whether this PR is required and has
desired effect.
Depends on https://github.com/openhab/openhab/pull/2623
> Make sure #anchor is observed by WebView sitemap elements.

- mobile/src/main/res/layout-v21/openhabwidgetlist_frameitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_chartitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_coloritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_fragment.xml
- mobile/src/main/res/layout/openhabwidgetlist_frameitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_genericitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_groupitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_icontext.xml
- mobile/src/main/res/layout/openhabwidgetlist_imageitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_rollershutteritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_sectionswitchitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_sectionswitchitem_button.xml
- mobile/src/main/res/layout/openhabwidgetlist_selectionitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_setpointitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_slideritem.xml
- mobile/src/main/res/layout/openhabwidgetlist_switchitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_textitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_videoitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_videomjpegitem.xml
- mobile/src/main/res/layout/openhabwidgetlist_webitem.xml
Fixes #130.
This fixes the issue that huge whitespace is displayed in case no icon is available for an item in the sitemap.
The main solution was to define a fixed layout_width/layout_height for the MySmartImageView. Besides that, I have formatted the xml files and extracted the icon and text into a seperate xml which is not included by the other layout xmls.
This pull requests contains two commits, one with the actual changes and another one with only formatting adjustments (for easier review).
> Fix issue with huge whitespace in case no icon is displayed in sitemap

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
I found an issue when loading chart images. If it takes some time for
the image to load the image from a recycled image view is displayed.
After some time the correct image loads, but it’s confusing because it
looks like the image has already been loaded. I fixed the problem by
setting the image drawable to null before loading the image url.
I also added multidex support because I couldn’t build the app without
it and Android Studio removed two unused imports.
I’ve already tested this and is seams to work very good. Please merge
this to your app.
Signed-off-by: David Masshardt <david@masshardt.ch> (github:
TheNetStriker)
> Clearing recycled chart image

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABItem.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
Thanks to https://github.com/eclipse/smarthome/pull/1253 development we now can distinguish between switch and rollershutter item and display proper control widget for the group.
Bug: https://github.com/openhab/openhab.android/issues/141
Signed-off-by: Robert Michalak <rbrt.michalak@gmail.com>
> Enable display of proper rollershutter control for rollershutter groups.

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB1Sitemap.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB1Widget.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Sitemap.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABSitemap.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABSitemapPage.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidget.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidgetDataSource.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/drawer/OpenHABDrawerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/test/java/org/openhab/habdroid/model/OpenHAB1WidgetTest.java
- mobile/src/test/java/org/openhab/habdroid/model/OpenHAB2WidgetTest.java
When using OpenHAB2, fetch icons from the ESH icon servlet.
Add an abstract method getIconPath() to OpenHABWidget and
OpenHABSitemap that will fetch the correct path for the
server side icon, it will behave differently depending on
OpenHAB version.
Use factory method when creating OpenHABWidgets instead of
a constructor.
Add testCompile dependency to org.json to be able to stub
JSONObject.
Fixes #145
Signed-off-by: Hans Hazelius <hans@hazelius.se>
> Fetch icons from correct path for OH2

- mobile/src/main/java/org/openhab/habdroid/util/Util.java
I have >30 sitemaps. It's difficult to find the one i'm looking for, because the sitemaps in the drawer are completely unsorted.
This patch sorts the Openhab1 sitemaps by label.
> Sort the sitemaps in drawer by label.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
Fetch uuid and api version from openHAB2
and display them in the info dialog.
Fixes #191
Signed-off-by: Hans Hazelius <hans@hazelius.se>
> Update info fragment for openHAB 2

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
Fixes the display of charts in case a group item is to be dislayed (see https://community.openhab.org/t/no-rrd4j-persistence-items-available-via-rest-access-and-in-habdroid/14189)
Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>
> Fix display of charts for group items

- mobile/src/main/java/org/openhab/habdroid/util/Util.java
does the same thing, but without the empty if {}
> simplified some logic in overridePendingTransition()

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java
these catches are identical, and probably generated by an editor at some stage. Collapsing them to make the code easier to read.
> Collapse duplicate exception catches

- mobile/src/main/res/layout/openhabnotificationlist_item.xml
> Fixes #218

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
By default the WebView is not 100% HTML5 compatible. This PR enables [DOM storage](https://en.wikipedia.org/wiki/Web_storage) which is for instance required when you want to create a WebView showing a [Grafana](https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing) panel with tooltip support (JavaScript).
> Improve WebView compatibility by enabling DOM storage

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidgetDataSource.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/xml/preferences.xml
- mobile/src/test/java/org/openhab/habdroid/model/OpenHAB2WidgetTest.java
Add support for icons in svg format. 
Add use a bugfixed copy of androidsvg from https://github.com/BigBadaboom/androidsvg.
When androidsvg is corrected the copied classes can be replaces with a dependency to the official library instead.
> Support for icons in svg format

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
This change restores the ability to select an NFC option after a long press on a Switch item. 
The type is currently checked to match "SwitchItem" but the actual type value is "Switch" so I modified the if logic to check for both variations.
Issue #117 has a lot of comments, so I'm not sure if this will complete it. At the least, it is part of the solution.
Signed-off-by: Gregory Moyer <moyerg@syphr.com>
> References #117 - restore NFC functionality to Switch items

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/de/duenndns/ssl/MemorizingActivity.java
- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/core/NetworkConnectivityInfo.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/res/layout/openhabinfo.xml
- mobile/src/main/res/layout/openhabwritetag.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
- wear/build.gradle
WHAT THIS DOES:
* Runs in API 14+
* Targets API 25, buildtools 25.0.2
* Uses latest gradle & updated libraries
* Includes multiwindows support for Chromebook/Nougat
* Adds build timestamp to app info in settings
* Use AppCompatActivity everywhere
* Minor lint warning fixes (there are many more unaddressed)
PULL-REQUEST NOTES:
* DSA is not supported by Google after API 23.  Use EC instead I guess (see the [commit](https://github.com/fat-tire/openhab.android/commit/b19240f4cd359e24ab34dfefb9afe8a3d3ea666d#diff-b8963974f554d6698e36b7b2a0fa790aR151) for how this was handled).
* Has only been tested on API 14 emulator but seems to run fine.
* Do not manually request fine location or other permissionw w/new runtime permissions system.
I can't find where it is invoked and would rather do it …
> Update to latest API+tools+gradle+misc.

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
- mobile/src/main/res/values/strings.xml
The String is used as a "oposite" of connecting to a remote url, so it should be changed to "local". This already happend in at least the German and Spannish translation.
> More consistent strings

- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-ja/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-nl/strings.xml
- mobile/src/main/res/values/strings.xml
app_name, openhab_service_type, openhab_demo_url should always be the same.
There seems to be unnecessary ">" in the xml files. Do they have any meaning?
> Make a few strings non-translatable

- mobile/src/main/res/xml/preferences.xml
Light themes are always default. The light theme uses the openHAB "orange", but the dark theme is just grey.
This also fixes the issue, that no radio button in the theme selection is checked after installation.
> Set default theme to light

- mobile/src/main/java/org/openhab/habdroid/core/NotificationDeletedBroadcastReceiver.java
- mobile/src/main/java/org/openhab/habdroid/core/notifications/GoogleCloudMessageConnector.java
- mobile/src/main/java/org/openhab/habdroid/core/notifications/NotificationSettings.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/java/org/openhab/habdroid/util/MySyncHttpClient.java
- mobile/src/main/res/layout/openhabinfo.xml
- mobile/src/main/res/values/strings.xml
Instead of hardcoding the sender ID of myopenhab.com in this otherwise
dynamic app, the sender ID, which is used to register the device to a
specific service account in Google Cloud Messaging, is now queried
dynamically using a new notification settings api endpoint on the
openhab-cloud endpoint.
When a user adds a new openHAB remote URL (in fact, whenever the openHAB
main activity is created), the app will start registering the device in
the used openhab-cloud instance and GCM. After all data checks, the app
will query the /api/v1/settings/notifications endpoint of this
openhab-cloud instance. This endpoint will return a JSONObject with
information about the notification settings to use (currently the GCM
sender ID only).
The returned sender ID will be used to register the android device …
> Implement dynamic GCM sender ID

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABTracker.java
Instead of requiring a local url to be configured in order to use the
remote url, the app now tries to connect using the local url first. if
this does not work (not configured or not reachable), it does the same for
the alt / remote url. And only if this fails, too, the service discovery
is started.
This makes testing of openhab-cloud locally a bit easier, and is what I
would expect as a user.
> Do not start discovery service if only remote url is configured

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
If the voice recognizer is not available the microphone icon is not present, so IMO the error message is not necessary
as discused in #282
> Remove voice recognizer error

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/SpinnerClickAdapter.java
This streamlines the behaviour of the app and of the basic UI, which now
behave in the same way. The selection item now always sends an update to
the openHAB item, no matter, if the state changes or not, the user just
needs to select one item.
Fixes #305
> Send an update of a selection item, even if the state does not change

- mobile/src/main/java/org/openhab/habdroid/util/MyHttpClient.java
- mobile/src/main/res/values/strings.xml
To trust self-signed certificates, there's a setting, which allows the
user to bypass the certificate trust check. Until now, the setting was not
observed anymore since the change to okhttp3, which is fixed with this
commit.
Fixes #310
> Observe the setting, that all certificates should be trusted

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/MyAsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MyHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MySyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/test/java/org/openhab/habdroid/util/MySyncHttpClientTest.java
If the connection to the remote host could not be established, the app
creates a fake response with the error message and status code 500 for the
notification settings sync hhtp request. However, until now, the creation
of this Fake response failed, as the Response builder requires some data,
which was not given so far.
This also refactors the MyHttpClient sslSetup method, which does not need
to get the whole context passed to it and therefore the constructors of
MyAsync and MySyncHttpClient does not need this neither. It now takes a
boolean argument, which indicates, if hostnames of a ssl cert should be
ignored or not.
Fixes #315
> Fix crash if "No route to host"

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
Before this commit, the app tried to restore the fragments and widgets
opened before the app was closed (or killed by the system). However, this
more or less failed mostly and resulted in the problem, that, if the user
choosed a specific widget sub-section, the saved fragment was loaded (with
the title of the new fragment), instead of the new one.
This commit removes this logic. The app now does not try to restore the
state of the app anymore, after it was closed. The state is only
preserved, if the app comes to the foreground again, without being stopped
in the meantime.
Fixes #246
> Do not restore state after the app was stopped

- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
SVG#getDocumentViewBox() could return null, if no viewBox is present in
the provided SVG. In this case, assume, that the SVG size is 16x16px
(probably not the best values, but if the the viewBox is missing, it's
already a pretty weird case and the behaviour is more or less undefined,
this now just prevents the app from crashing).
Fixes #330
> Fix NullPointerException when no viewBox is part of SVG

- mobile/src/main/res/layout/openhabwidgetlist_selectionitem.xml
This has several advantages:
1. Consistent width
2. Same behavior in app and basic ui
3. Better for tablets and large smartphones
Fixes #344 
Couldn't make a screenshot of how it is now, but here is a screenshot after:
Maybe we should add a radio button.
> Use popup for selection items

- mobile/src/main/res/xml/preferences.xml
> For security reasons, SSL hostname checks should be enabled by default

- mobile/build.gradle
- mobile/src/main/res/layout/openhabwidgetlist_sectionswitchitem.xml
I have tested this on a tablet. but it may need some testing on a smartphone.
Fixes #121 and #359 
> Fix overlapping item label and selection switch

- mobile/src/main/java/org/openhab/habdroid/core/GcmIntentService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
If a notification from the systems notification bar is selected, the app
now opens the notifications fragment, if it is available currently
(openHAB remote url with username and password is used).
It also shows an alert box with the message content of the selected
message, if the message was added to the intent (should always happen).
This will happen regardless if the notification fragment is opened or not
to show the full message to the user (again).
Fixes #379
> Open Notifications fragment when notification is selected

- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
The problem is that all images (icons, charts and external images) are
rendered in the same format and the svg libary will fail if it gets a
png.
At this point we dont really have to read the preferences since
mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java Line
21 inserts format=(format here) in the url and we can parse this url.
Fix #286
I'm not sure if that is the best solution.
> Display images as PNG when icon format is set to SVG

- mobile/src/main/res/values-el/strings.xml
This PR fixes the Greek translation info_openhab_gcm_not_connected String referenced in PR #337
> Fixed Greek translation for gcm status printing

- mobile/src/main/java/org/openhab/habdroid/core/notifications/NotificationSettings.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABFragmentPagerAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
Accessing notifications with the local URL can't work, as the local URL is
mostly the openHAB URL directly, which does not provide the expected
notifications api. Instead, if a remote URL is set, use this for the
notifications fragment always.
Fixes #253
> Always use altUrl for Notificatiosn fragment

- mobile/build.gradle
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/CheckIntroAndCancel.java
This PR adds the espresso ui testing framework. The first test checks if everything in the intro is present and cancels it. The second test goes through all intro slides, selects the demo sitemap and checks if some entries are present (mic and dropdown menu buttons, sitemap groups, slider, colorpicker, rollershutter, etc.).
> Add two espresso ui tests

- mobile/src/main/res/values/strings.xml
In Paper UI they are called "Bitmap" and "Vector", but I think "Vector graphic" is more common.
> Change icon type name

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/main/res/menu/main_menu.xml
- mobile/src/main/res/xml/preferences.xml
The possibility to clear the image cache is not an option to the currently
viewed sitemap or section or whatever. It also shouldn't be necessary to
have this option in such a prominent component as the options menu.
Therefore, and for preparation to remove the options menu completely, the
menu is moved to the settings (next to the icon type selection).
Fixes #478
> Move the clear image cache from the options to the settings menu

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
The problem is that I couldnt find a way to reproduce, so I cannot test if that really fixes the problem. I have the "fix" from here: https://stackoverflow.com/questions/18662239/android-view-windowmanagerbadtokenexception-unable-to-add-window-on-buider-s/31986885#31986885
Fixes #471
> Fix crash #471

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Changed
````
Sitemaps
Notification
-------------
Settings
About
````
to
````
Sitemaps
-------------
Notification
Settings
About
````
> Show seperator on correct position

- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-el/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-ja/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-nl/strings.xml
- mobile/src/main/res/values-ru/strings.xml
- mobile/src/main/res/values/strings.xml
The strings settings_openhab_icon_format_png and settings_openhab_icon_format_svg are still in use, but the original string changed, so I remove them here and the translator can translate the new string.
> Remove some unused ressources

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/menu/main_menu.xml
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Instead of a menu entry "Select default sitemap", there's now a setting in
the Preferences menu, which allows the user to "claer the default sitemap"
selection, if there's already a selection. Once cleared and going back to
the main activity, the user is prompted to select a new default sitemap.
Fixes #479
> Move "Select default sitemap" to Preferences

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNFCActionList.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/res/values/strings.xml
The feature to create a NFC tag for a sitemap page is re-introduced with
this commit. However, it for now lifes in the long-press option of any
item on the current sitemap, instead of in the options menu.
Fixes #527
> Re-introduce link to sitemap page for NFC write tag actions

- mobile/build.gradle
English (XA) and ... (XB) are pseudo translations for testing. This
changes will enable them in the app, when you switch the phone to one of
these languages.
https://androidbycode.wordpress.com/2015/04/19/pseudo-localization-testing-in-android/
> Enable pseudo translations for testing

- mobile/src/main/java/org/openhab/habdroid/model/OpenHAB2Widget.java
See https://community.openhab.org/t/openhab-android-habdriod-december-2017-version-rollershutter-status-not-shown-correctly-anymore/37436
> Fix icon for rollershutter

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
Fix #548 
Instead of crashing, because snackbar is not implemented here, fall back to toast. Snackbars are not available here, since they must be attached to a parent layout, which doesnt exist, when the user is on the home screen and uses the voice widget.
> Make toast default

- docs/USAGE.md
- mobile/src/main/res/values/strings.xml
A few suggestions after testing the new release.
* In the settings menu the same capitalization is used.
* Normalize the use of "Full Screen" vs. "Fullscreen" @digitaldan [which version](https://english.stackexchange.com/questions/162421/fullscreen-or-full-screen) do you prefer?
* Remove redundant "openHAB"
* When long-pressing an element, the "Please select NFC tag action comes as a surprise because a new user won't know about that function. I've adapted the string to better introduce it. Ideally an new menu entry should be added to the hamburger menu ("Write to NFC") explaining this function. 
This PR is just a **first suggestion**! Feel free to comment or adapt.
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> Improve english UI strings

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABAboutActivity.java
- mobile/src/main/res/layout/fragment_about.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/values/themes.xml
This dependency allows us to easily show information about libraries used
in the app, including the name, the description and a link to the info
page (source code, or any other website).
> Add AboutLibraries to the App

- mobile/src/androidTest/java/org/openhab/habdroid/OpenHABProgressbarIdlingResource.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
And also make the test not dependant on the speed of loading
demo.openhab.org. It now wait's until the progressbar in the header
disappears before any further action is taken.
> Make BasicWidgetTest working again

- mobile/src/androidTest/java/org/openhab/habdroid/TestUtils.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/CheckIntroAndCancel.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/IntroActivityTest.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
Some tests may require some additional or specific preferences to be set
to specific values in order to work correctly.
To achieve that, this commit adds a Before method to both instrumentation
tests, which will set these required preferences before starting the
activity. It also removes the "go through intro" from the BasicWigetTest2,
which is already tested in the CheckIntroAndCancel test, so there's no
need to test it again. It is also out of scope of the test case.
> Make instrumentation tests more independant from each other

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values-de/strings.xml
- mobile/src/main/res/values-el/strings.xml
- mobile/src/main/res/values-es/strings.xml
- mobile/src/main/res/values-fr/strings.xml
- mobile/src/main/res/values-lt/strings.xml
- mobile/src/main/res/values-ru/strings.xml
- mobile/src/main/res/values/strings.xml
In debug mode url, username, password and stacktrace will be shown, when connections errors occure.
> Extend dialogs in debug mode

- .pullapprove.yaml
Fixes #585
@kaikreuzer I think you have setup pullapprove on https://github.com/openhab/openhab2-addons. Can you add this repo on https://pullapprove.com ?
> Add pullapprove config

- .travis.yml
I think no one reads ~3000 lines of lint errors and it blows up the
build log.
> Dont show lint results in travis

- mobile/src/androidTest/java/org/openhab/habdroid/ProgressbarAwareTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/TestWithIntro.java
- mobile/src/androidTest/java/org/openhab/habdroid/TestWithoutIntro.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/IntroActivityTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/VoiceRecognitionTest.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Instead of quering for an intent, which is used for implementation, we'll
use official API to check, if voice recognition is available on the
device. This will change the intent checked from ACTION_RECOGNIZE_SPEECH
to SERVICE_INTERFACE.
Also: Extract the Voice recognition test from the BasicWidget test and
execute it only, if voice recognition is actually available on the
instrumented device.
> Use SpeechRecognizer.isRecognitionAvailable() to check if available

- .travis.yml
- build.gradle
- mobile/build.gradle
See this PR for an example: https://github.com/mueller-ma-bot/openhab.android/pull/1
I also tested Sputnik there, but this is not included in this PR.
@digitaldan This is just the config for codecov. To add it, go to their website and login via github.
Hopefully this will help to increase the code coverage. Current is ~6%
> Add codecov and run android tests via travis

- mobile/src/full/java/org/openhab/habdroid/core/GcmIntentService.java
* Use the real message as text, not "openHAB". See for reference: http://cdn.androidbeat.com/wp-content/uploads/2016/03/bundled-notification.png
* Add accent color
Fixes #603
I havent really tested it, maybe someone can create a test notification.
> Improve notification design

- mobile/src/androidTest/java/org/openhab/habdroid/TestWithIntro.java
- mobile/src/androidTest/java/org/openhab/habdroid/TestWithoutIntro.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.java
- mobile/src/androidTest/java/org/openhab/habdroid/ui/IntroActivityTest.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
Fix #595
The sitemap name is also shown in the settings. @FlorianSW Whats the best way to show the label there?
> Use sitemap labels instead of name in the sitemap selection dialog

- mobile/src/main/AndroidManifest.xml
It is currently not used anywhere, so we shouldn't ask for this
permission, which can provide access to private information.
Fixes #244
> Remove unused permission from the app

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABSitemap.java
- mobile/src/test/java/org/openhab/habdroid/model/OpenHABSitemapTest.java
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.java
Fixes #622
I found out, that the field "leaf" isnt set in OpenHAB2Sitemap. Is this intended?
> Display sitemap name when no label is present and add sitemap tests

- mobile/src/main/java/org/openhab/habdroid/core/GcmBroadcastReceiver.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABAboutActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABInfoFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.java
- mobile/src/main/java/org/openhab/habdroid/util/MyKeyManager.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
Having them static can cause unexpected side effects (e.g. when
recreating activities or fragments), and in most of the cases they
didn't need to be static to begin with.
> Don't unnecessarily make variables static.

- checkstyle.xml
This change was a great improvement to a local checkstyle run on MainActivity. I tried it in two repos, but stickler is still throwing tons of indent rule violations.
This has two possible reasons:
1. The checkstyle config is cached
2. It checkstyle config from the PR branch is taken
Anyway I would like to merge this one and @maniac103 please rebase #650 after this is merged.
> Fix checkstyle Indentation module

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
- mobile/src/main/res/xml/preferences.xml
The default value does not need to be one of the elements in entries, but
one of the elements entryValues, otherwise the default value returned by
SharedPreferences#getString() will be the display value, not the correct
value itself.
Fixes #670
> Set the correct default value of icon format ListPreference

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/values/strings.xml
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.java
The cause of the error a CertificateException and its cause is
CertPathValidatorException, so we need to call .getCause twice.
> Display correct ssl error message

- README.md
I have noticed delayed loading of the shield.io codecov badge and hope it will load faster with the badge hosted by codecov.
> Use official codecov badge

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/values/attrs.xml
TextView.setColor() overwrites the default ColorStateList, so we have to
store it in order to restore it later.
Fixes #690
> Fix resetting widget TextViews back to default color.

- assets/store_descriptions/generate_and_validate.sh
The intention behind this commit is to disallow new line or similar
chars in store descriptions.
Since crowdin inserts two lines comments, we need to check if sharp count > 2
@ThomDietrich
> Disallow # and \ in store descriptions

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
Instaed of using the getActivity method of an object, which may already
been outdated and return null in this case, use the View#getContext method
to get the current context of the on click action when closing the "swipe
to refresh" explanation snackbar.
Fixes #707
> Fix NPE when closing snackbar when already navigated back

- mobile/src/full/java/org/openhab/habdroid/core/GcmIntentService.java
Successor of #673, now with clean code from a fresh fork (without all the other commits)
Ensures that notifications show the actual event/sending time instead of the reception time on the device when you have a weak signal and receive the messages late.
> Time in notification is now is sending time / 2nd try

- .github/issue_template.md
GitHub has both apks, so we don't know which flavor is used.
> Change "installation source" to "build flavor"

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
Doing so works around the about library activity not setting an action
bar overlay appropriate for dark action bars when using it together with
a custom activity theme.
Signed-off-by: Danny Baumann <dannybaumann@web.de>
> Use about library fragment instead of activity.

- mobile/src/main/res/values/dimens.xml
> Fix padding in about libraries fragment

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
As getMaterialAboutList() is running in a background thread, the
fragment might become detached while the thread is running, so better
use the passed-in context.
> Use given context to populate about fragment strings.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
Show a spinning wheel during the retry, and don't allow multiple server
queries to be active at the same time.
> Improve connection retry UX.

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
The HTTP client created by PageConnectionHolderFragment lacked authentication set up. Now we're using the client provided by the connection.
> Fix page load if authentication is used.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/res/layout/openhabwidgetlist_frameitem.xml
Don't render divider shadow if frame is the first item, and center text
in the visible area.
> Improve look'n'feel of frame widget.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
Don't temporarily set highlight on click, but only if really needed in
two-pane layout.
Closes #718
> Simplify widget list selection highlight code.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationAdapter.java
Causes 404 when fetching icon.
> Fix stray slash in notification icon URL generation.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
Makes sure no HTTP connections to the previous connection are made.
> Properly clear fragments and view pool after connection changes.

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABNotification.java
The icon and severity members are not guaranteed to be present, while
the message member is expected to be present.
(Fixes NPE when opening notifications page)
> Fix OpenHABNotification object annotations.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java
Don't prematurely change preferences, and don't pass server URL to
selection UI: As we use the client certificate for both local and remote
server, showing it is unneeded; and additionally the previous server
parsing code caused a NPE if remote server wasn't set.
Fixes #802
> Fix KeyChain handling in preferences.

- mobile/src/beta/res/values/strings.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/stable/res/values/strings.xml
There might be a language where the word "Beta" is usually translated.
Is it in English `openHAB Beta` or `openHAB beta`?
> Make app_name for beta builds translatable

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
Updating the content controller while not started is not allowed.
Fixes a crash happening when clicking the notification while the app is not open.
> Defer main activity intent processing until onStart().

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetListFragment.java
Otherwise, the highlight is used when two-pane controller is replaced by
one-pane controller after device rotation, but we never want one-pane
layout to have those highlights. As the two-pane controller reapplies
the highlight when restoring fragments, storing the link as instance
member is sufficient.
Fixes #791
> Don't persist highlighted page link to fragment arguments.

- mobile/src/main/java/org/openhab/habdroid/model/OpenHABWidget.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java
- mobile/src/test/java/org/openhab/habdroid/model/OpenHABWidgetTest.java
Do this even if the useImageCache flag is set to false and use that flag
only to decide whether to do a new GET request or not.
When not doing so, images will be (temporarily) shown in wrong spots
when scrolling lists up and down.
Fixes #829 and probably also #826.
Signed-off-by: Danny Baumann <dannybaumann@web.de>
> Always try to load images from cache first.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
The server's density calculations are center around a default density of
96 dpi. In Android, the default is 160 dpi; thus the charts are scaled
too much (fonts and lines are disproportionally large/thick).
> Improve chart scaling.

- mobile/src/full/java/org/openhab/habdroid/core/GcmRegistrationService.java
- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/core/connection/CloudConnection.java
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABNotificationFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/test/java/org/openhab/habdroid/core/connection/DefaultConnectionTest.java
Previously those path segments were simply stripped off, so a base URL
in the form 'http://server.domain/some/path' with the endpoint
'/rest/bindings' became 'http://server.domain/rest/bindings'.
As the newly called method interprets a trailing slash in the URL as an
empty path segment, we have to strip off those trailing slashes from the
passed-in URLs, so that the example above resolves to
'http://server.domain/some/path/rest/bindings'.
Fixes issue reported at https://community.openhab.org/t/version-2-1-0-broken-wrong-url/43999
> Fix URL handling for cases where server URL contains path segments.

- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- travis/bump-versioncode.sh
- travis/uploads.sh
With the previous setup F-Droid isn't able to pick up beta builds as it
needs versionName, versionCode and applicationId in one file.
See https://gitlab.com/fdroid/fdroiddata/issues/1196
> Move versionCode and versionName to build.gradle file

- assets/store_descriptions/en-US/strings.xml
- assets/store_descriptions/generate_and_validate.py
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/res/drawable/ic_security_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
A link to the privacy policy has been added to the about page:
In the Play Store it is possible to add a link to the privacy policy as
metadata, but in F-Droid you cannot, so we have to add it to the
description.
The note about the anti features is nice to have. It explains why the
app entry contains the line "The app has features you may not like."
@kaikreuzer Can I use https for all links to openhabfoundation.org?
>  Add note about privacy policy

- assets/store_descriptions/en-US/strings.xml
- assets/store_descriptions/generate_and_validate.py
See https://github.com/openhab/openhab-android/issues/403#issuecomment-389934693
@kaikreuzer @digitaldan I created a developer page in the play store. It's basicly an image and website link added to the [default app listing](https://play.google.com/store/apps/developer?id=Twitter,+Inc.) of our apps.
For the preview I have taken an image from mysplash, so we don't have to credit the author and can use it for free: https://play.google.com/store/apps/dev?id=7475306295333689578 I think the usage of the openHAB logo for this image would be an over-use of it.
> Add beta note to play store description

- mobile/src/main/java/org/openhab/habdroid/core/OpenHABVoiceService.java
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
In line 897 it's checked wheter a speech recognizer is available. If
it's not the mic icon is hidden, so launchVoiceRecognition() cannot be
called.
> Remove unneeded try catch in voice command funtionality

- assets/store_descriptions/en-US/strings.xml
As a replacement for #881, update the description in the source rather than the intermediary file.
As noted in the original PR, the short description shows up in F-Droid as:
openHAB - openHAB client for Android
It's more useful to describe what the application is.
> Update short description

- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
Otherwise the icons are cut when their height/width is higher than the
viewbox.
Fixes #728
> Change svg height/width to "100%"

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
Only call notifyDataSetChanged() if needed, that is, if the newly sent
list of widgets is structurally different from the old list of widgets.
Closes #586
Signed-off-by: Danny Baumann <dannybaumann@web.de>
> Optimize widget list update handling.

- assets/store_descriptions/en-US/strings.xml
Links with F-Droid syntax don't work when the metadata is in the app repo. See https://gitlab.com/fdroid/fdroiddata/issues/1222
> Use HTML link in F-Droid description

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
See #935
I've checked the openhab cloud sources and couldn't find any similar code where the error is created by openhab cloud: https://github.com/openhab/openhab-cloud/blob/master/routes/index.js#L347
> Improve error message when oh is offline, but cloud is running

- mobile/src/main/AndroidManifest.xml
Nothing is excluded from the backups, so the username and even the
password would be uploaded to Google Drive. Thus I'm disabling the
backups and we might want to enable it again when the url, user and
password settings are moved to a database.
> Disable backups

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/network_security_config.xml
Adding a security config requires our trust manager implementation to
implement the variant of checkServerTrusted() that accepts a host name,
but we can't provide that hostname from within MTM.
This reverts commit ac986b18f8c94336f333611b95021cefdc035fa2.
Fixes #937
> Revert "Use networkSecurityConfig to disallow http to myopenhab.org" (#908)

- mobile/src/full/res/values/strings.xml
> Always include %d in "one" because translators will need to use
> %d for languages where "one" doesn't mean 1 (as explained above)
from https://developer.android.com/guide/topics/resources/string-resource#Plurals
I've tested this in English and it works like before, but I haven't tested it in a language where it makes a difference, e.g. Russian.
> Use %d instead of 1 in plurals strings

- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java
There's a condition where widget icons are loaded incorrectly:
- Have a WidgetImageView which just loaded an icon
- Go to another page (previous views are detached)
- Go back to initial page (previous views are reattached, but not
necessarily in the same spot)
In step 3 of that scenario, views are likely to use a cached bitmap
instead of loading them again, in which case mLastRequest isn't properly
cleared out and re-triggered later when onAttachedToWindow() is called.
As the request points to the URL of the last spot, the wrong icon is
loaded in that case. Fix this by properly clearing out the last request
when assigning a new URL.
Fixes #955
> Fix wrong icons being loaded if views are re-used

- mobile/src/main/AndroidManifest.xml
> Though this does not change the default behavior, it explicitly states that your application should only be installed on the internal storage and serves as a reminder to you and other developers that this decision has been made.
from https://developer.android.com/guide/topics/data/install-location
The removed code has been disabled four years ago and we don't use
Analytics anymore.
> Add "installLocation" to Manifest

- mobile/src/full/AndroidManifest.xml
- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.java
- mobile/src/full/java/org/openhab/habdroid/core/GcmInstanceIDListenerService.java
- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
- mobile/src/full/java/org/openhab/habdroid/core/GcmRegistrationService.java
- mobile/src/test/java/org/openhab/habdroid/core/CloudMessagingHelper.java
Otherwise crashes might occur when app is in the background and
connectivity changes on Android 8+.
Fixes #953
Signed-off-by: Danny Baumann <dannybaumann@web.de>
> Convert GcmRegistrationService to a JobIntentService.

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java
Webviews are recycled and need to be cleared before being re-used.
Otherwise the old webview content is shown until the new one is loaded.
Closes #948
> Clear webviews before being re-used

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
- mobile/src/main/res/values/strings.xml
In some case the try catch is needed. See
https://console.firebase.google.com/project/openhab-mobile/crashlytics/app/android:org.openhab.habdroid/issues/5b755c156007d59fcdf12bc8
(only visible to the openHAB staff).
I updated the code to open the Google app in any app store. Some users
might use YALP store or any other custom Play Store (or Amazon app
store). For users without any additional app store the Play Store is opened.
> Revert "Remove unneeded try catch in voice command funtionality (#899)"

- mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java
They're already correctly handled via onStart() ->
onAvailableConnectionChanged(). As that path also correctly clears the
sitemap list if there's no available connection, there's no reason to
also do the update via onCreate().
Fixes #986
> Don't update sitemap drawer items in activity's onCreate().

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/res/drawable/ic_high_quality_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Fixes #440
This issue can already solved server-side by setting a max width for
charts in Paper UI, but it's not easy to find for the user.
@lolodomo Do you want to test this?
Low res. Please note, that my device has a quite low resolution.
High res:
> Fix slow chart loading issue

- build.gradle
- mobile/build.gradle
We don't need it, because we don't use CodeCov anymore.
Fixes #1070
> Remove jacoco-android

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
Fixes
````
java.lang.NullPointerException:
at org.openhab.habdroid.ui.WidgetAdapter$SetpointViewHolder.onClick (WidgetAdapter.java:819)
at android.view.View.performClick (View.java:6897)
at android.view.View$PerformClick.run (View.java:26101)
````
> Fix NullPointerException in Setpoint

- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
In Oreo or higher Notification channels should be used to change the
notification sound and vibration.
@maniac103 Can you check the vibration setting as I don't have a physical device with O+?
> Hide notification settings when running Oreo or higher

- mobile/src/main/java/org/openhab/habdroid/util/MjpegInputStream.java
`getEndOfSeqeunce()` may return -1 which is an illegal value for array
size.
> Fix NegativeArraySizeException in MjpegInputStream

- mobile/src/full/java/org/openhab/habdroid/core/GcmMessageListenerService.java
NotificationManagerService on M discards the group children and only
shows the summary, but our summary generation code expects the children
still to be present. As we don't have local information about the
child notifications, just prevent summaries from being used on M.
Fixes issue mentioned in https://community.openhab.org/t/notification-does-not-show-contents-in-pop-up/57388
> Don't use notification grouping on Android M (API 23)

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
Previously we didn't handle ServerAliveEvent and SitemapChangedEvent,
but treated all events as if they were SitemapWidgetEvents. Fix that by
looking at the TYPE attribute.
Closes #1082
> Fix SSE sitemap event handling.

- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
When the app is offline and the user opens the settings, some settings
like chart scaling are missing and it might be confusing to have that
settings "just sometimes". Since we don't support multiple servers
(except demo server, which is excluded), saving the flags to prefs
seems save to me.
> Save server properties for later use

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/res/drawable/ic_signal_wifi_0_bar_black_24dp.xml
- mobile/src/main/res/drawable/ic_signal_wifi_off_black_24dp.xml
- mobile/src/main/res/layout/fragment_status.xml
- mobile/src/main/res/values/strings.xml
* Add ability to show a second hint and/or button.
Discorvery failed:
* Discorvery failed hint and open settings button (old)
* Demo mode hint and enable demo mode button (added)
No network available:
* Enable wifi button (added)
No remote server:
If wifi is enabled:
* "No remote server configured" hint and open settings button (old)
If wifi is disabled:
* "No remote server configured" hint and open settings button (old)
* Enable wifi button (added)
Fixes #1115
> Enhance status fragments

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
The server doesn't return invisible widgets in its REST API response, so
if we're seeing an event for an unknown widget chances are high it's for
a widget that previously was invisible.
Closes #1094
> Reload widgets when encountering events for unknown ones.

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/res/layout/fragment_fullscreenwebview.xml
* Don't reset HABPanel on device rotation. Closes #1169
* Set the webview background to transparent. Avoids white flash when
opening HABPanel with a dark app theme.
* Make fragment reusable for other websites
> Improve HABPanel viewer

- mobile/build.gradle
Reverts openhab/openhab-android#1199
Fixes crash at startup on Kitkat.
> Revert "Bump okhttp from 3.12.1 to 3.13.1"

- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
> Use primitive types if possible

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.java
IllegalFormatPrecisionException (#1221) and MissingFormatWidthException
(reported via Firebase)
> Catch more exceptions in ParsedState

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
mAuthHeader is only public for unit testing (marked by the
VisibleForTesting annotation), so keep the usage of the member variable
private to the HttpClient class. Doing so also avoids code duplication.
> Keep authentication header an implementation detail of HttpClient.

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
Previously, there were two public methods in HttpClient that were needed
only by the SSE code. Since they always were used together anyway, we
can as well combine them into one and keep HttpClient public API more
consise.
> Clean up public methods needed for SSE in HttpClient.

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.java
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
Especially for local connections, like WiFi or maybe VPN, too, a
connection may not be "available" (~ connected to the internet) once it is
"connected". To allow a connection to do whatever is needed to do, wait up
to 2 seconds (in 10 200ms chunks) for the connection to become available.
If it is not available after this timeframe, the connection is returned as
"not reachable".
Fixes #755
Closes #780
Signed-off-by: Florian <florian.schmidt.welzow@t-online.de>
> Wait up to 2 seconds for connection to become available

- mobile/build.gradle
We need to stick to 3.12.x versions, as newer versions don't support API
level < 21 anymore.
Closes #1253
> Use consistent versions of OkHttp components.

- mobile/src/main/java/org/openhab/habdroid/model/Item.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
In particular, only send them for Number:<dimension> items, not for
plain Number ones.
> Only send unit in Setpoint/Slider updates if needed.

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/RecyclerViewSwipeRefreshLayout.java
- mobile/src/main/res/layout/fragment_widgetlist.xml
Current it's too easy to accidentally trigger swipe-to-refresh when
swiping to scroll the widget list upwards. Prevent that by only allowing
swipe-to-refresh if the widget list is already at the top when starting
the swipe gesture. This means if one wants to refresh while in the
middle of the list, one needs two swipe gestures.
See #1230
> Prevent swipe-to-refresh if swipe isn't started at top of page.

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.openhab.habdroid.model.ParsedState org.openhab.habdroid.model.Item.state()' on a null object reference
at org.openhab.habdroid.ui.WidgetAdapter$ColorViewHolder.showColorPickerDialog(WidgetAdapter.java:1106)
at org.openhab.habdroid.ui.WidgetAdapter$ColorViewHolder.onTouch(WidgetAdapter.java:1072)
````
> Fix NPE in color picker

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.openhab.habdroid.model.ParsedState.asString()' on a null object reference
at org.openhab.habdroid.ui.WidgetListFragment.onItemLongClicked(WidgetListFragment.java:146)
at org.openhab.habdroid.ui.WidgetAdapter.onLongClick(WidgetAdapter.java:350)
````
> Fix NPE im WidgetListFragment

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/util/Constants.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
It was possible to set fragment show/hide animations to be Android like,
iOS like or to disable them. The preference has been removed long ago,
so the code should be removed as well.
> Remove useless function overridePendingTransition()

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
````
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1870)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1893)
at android.app.FragmentManagerImpl.popBackStack(FragmentManager.java:805)
at org.openhab.habdroid.ui.PreferencesActivity.onOptionsItemSelected(PreferencesActivity.java:98)
at android.app.Activity.onMenuItemSelected(Activity.java:3527)
at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:436)
````
> Fix IllegalStateException in PreferencesActivity

- mobile/src/foss/java/org/openhab/habdroid/core/CloudMessagingHelper.java
- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.java
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
Fixes #560
On a device without Play Services it shows "Device registration failed: SERVICE_INVALID". No idea why SERVICE_MISSING isn't returned instead (https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult).
I can add a mapping error code => human readable message, but I'm not sure if it's worth to do so.
> Add failure reason to FCM status

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.java
Given SSE connections count against that limit, the default per-host
connection limit (5) is too low, as with that limit no further
connections can be made when reaching a sitemap nesting level of 5
pages. The OH HTTP server should be able to handle more connections, so
generally use the max concurrent request count (64).
Fixes #1329
> Relax per-host connection limit.

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.java
> Fix PreferencesActivity crash on API < 17

- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.java
- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.java
Move it to the correct place, and make it more lenient to also cover the 'latitude,longitude,elevation' case.
Fixes issue reported in https://community.openhab.org/t/mapview-in-android-app-does-not-show-the-location/73379
> Improve location parsing

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
Send state if there's one mapping. Toggle state if there are two
mappings and the current state is equal to one of the mappings.
Fixes #1328
@maniac103 Is there a reason why you have chosen to hide spare views instead of removing them from the radio group?
> Implement row click action for section switch

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
* Make normalizeUrl() log as debug, not error and print the actual url
* Prevent this stacktrace:
````
05-11 09:29:01.288 org.openhab.habdroid.beta W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
05-11 09:29:01.289 org.openhab.habdroid.beta W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
05-11 09:29:01.289 org.openhab.habdroid.beta W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:89)
05-11 09:29:01.289 org.openhab.habdroid.beta W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
05-11 09:29:01.289 org.openhab.habdroid.beta W/System.err:     at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
05-11 …
```
> Reduce verbosity when starting app

- mobile/src/androidTest/java/org/openhab/habdroid/ui/NfcTest.java
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.java
- mobile/src/main/java/org/openhab/habdroid/background/NfcReceiveActivity.java
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.java
- mobile/src/main/java/org/openhab/habdroid/core/VoiceService.java
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.java
- mobile/src/main/java/org/openhab/habdroid/model/Item.java
- mobile/src/main/java/org/openhab/habdroid/model/NfcTag.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/RecyclerViewSwipeRefreshLayout.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/UrlInputPreference.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
- mobile/src/main/res/values/strings.xml
Create a new scheme that is only used for item updates. This way we can
have a background responder for NFC item updates. It uses the framework
introduced in #1137.
If an old tag is used, we show a message to the user to renew his tag.
See https://github.com/openhab/openhab-android/issues/538#issuecomment-480483543
See #13 (Shorter parameter names and no sitemap require less bytes)
> Improve NFC item updates

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.java
- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.java
- mobile/src/main/java/org/openhab/habdroid/util/Util.java
Set supportsMultipleWindows for the WebView. This prevents the WebView from
following links with target="_blank", which previously were opened in the same
WebView, corrupting the UI. The same adjustment is also made for HABPanel, can
be good there too.
Also set WebWidget background to transparent; this enables to use transparent
HTML background. Useful for e.g. weather informers.
Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>
> [#1342] Improve web widget in BasicUI

- mobile/build.gradle
Fixed in https://github.com/BigBadaboom/androidsvg/issues/170
````java
Fatal Exception: java.lang.IllegalArgumentException: bad base-64
at android.util.Base64.decode(Base64.java:161)
at android.util.Base64.decode(Base64.java:136)
at android.util.Base64.decode(Base64.java:118)
at com.caverock.androidsvg.SVGAndroidRenderer.checkForImageDataURL(SVGAndroidRenderer.java:1939)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:1860)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:300)
at com.caverock.androidsvg.SVGAndroidRenderer.renderChildren(SVGAndroidRenderer.java:334)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:623)
at com.caverock.androidsvg.SVGAndroidRenderer.render(SVGAndroidRenderer.java:298)
at …
```
> Fix crash in svg parsing

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.java
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java
- mobile/src/main/java/org/openhab/habdroid/util/AsyncHttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.java
- mobile/src/main/java/org/openhab/habdroid/util/SyncHttpClient.java
Only enforce passed desired size in HTTP bitmap loading if needed, and
for charts it certainly isn't needed.
> Fix chart and image widget scaling.

- mobile/src/main/java/org/openhab/habdroid/model/Widget.java
We previously didn't update icon, label color and value color via SSE.
Fixes #1380.
> Parse missing fields from SSE update events.

- mobile/src/main/java/org/openhab/habdroid/ui/widget/ItemUpdatingPreference.kt
If the pref was set already, the help icon was accessed via
switch.isChecked -> onCheckedChanged before it was initialized.
(See https://github.com/openhab/openhab-android/pull/1356#issuecomment-504702834)
> Fix UninitializedPropertyAccessException in ItemUpdatingPreference.

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
Don't waste time with retries on closed connection, and retry SSE
instead of falling back to long polling.
May fix #1282
> Improve SSE failure retry logic.

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
We added items based on the sorted sitemap list and later referenced
them by their index, but looked up the index in the unsorted list.
Fixes #1421
> Fix sitemap entries in drawer opening wrong sitemaps.

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
ConnectivityManager.getNetworkCapabilities() might return null in case
the network can't be found.
Closes #1427
> Fix IllegalStateException.

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
* Only set on prefs click listener if ringtone and vibration prefs are shown. This way the constants Settings.ACTION_APP_NOTIFICATION_SETTINGS and Settings.EXTRA_APP_PACKAGE are guarded by an API check.
* Use elvis operator
* Explicitly set type for `prefs`
> Fix lint issues in PreferencesActivity

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
* Parse state as Float if step size is a Float. Fixes #1389
* Fix not showing min value, but one step over max value.
* Fix Setpoint if state is null. Fixes #1397
> Fix Setpoint widget

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
Renaming ItemPickerActivity to TaskerItemPickerActivity breaks
configured actions in Tasker. I want to rename it, before the Tasker
plugin goes live in the stable version.
> Make ItemPickerActivity abstract

- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
````
Fatal Exception: java.lang.IllegalArgumentException: SVG document is empty
at com.caverock.androidsvg.SVG.setDocumentHeight + 792(SVG.java:792)
at org.openhab.habdroid.util.ExtensionFuncsKt.toBitmap + 122(ExtensionFuncs.kt:122)
at org.openhab.habdroid.util.HttpClient$HttpResult$asBitmap$bitmap$1.invokeSuspend + 182(HttpClient.kt:182)
````
> Fix crash when parsing SVG

- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
````
Fatal Exception: java.lang.RuntimeException: Unable to start receiver org.openhab.habdroid.core.FcmRegistrationService$ProxyReceiver: java.lang.IllegalArgumentException: work must not be null
[...]
Caused by java.lang.IllegalArgumentException: work must not be null
at androidx.core.app.JobIntentService.enqueueWork + 518(JobIntentService.java:518)
at androidx.core.app.JobIntentService.enqueueWork + 501(JobIntentService.java:501)
at org.openhab.habdroid.core.FcmRegistrationService$ProxyReceiver.onReceive + 116(FcmRegistrationService.kt:116)
````
> Fix crash in FCM registration

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
The code already was prepared for this by allowing passing null as item,
we just need to use the correct JSON parser method that doesn't throw an
exception if the value is missing.
Closes #1437
> Correctly handle SSE events without item.

- mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
`if (dialog is AlertDialog)` was always wrong, because android.app.AlertDialog !=  androidx.appcompat.app.AlertDialog.
> Correctly disable 'ok' button if alarm item is empty

- mobile/src/main/res/values/strings.xml
Fixes lint issues in build log.
> Use positional formatting for strings with more than one substitution

- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/Constants.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/main/res/drawable/ic_lock_outline_grey_24dp.xml
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Users can set lock screen to:
* off (default)
* on
* Kiosk mode: MainActivity can be accessed without screen lock, but
prefs, about, etc. are locked
Fixes #1216
> Add lock screen

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Since we already re-check fullscreen in onResume(), there's no reason to
handle daydream separately since we go to a pause/resume cycle anyway
when daydreaming starts.
@digitaldan Do you remember what the reason for introducing this code was? I can't see any reason for doing this.
> Remove daydream receiver from MainActivity.

- mobile/src/androidTest/java/org/openhab/habdroid/ui/BasicWidgetTest.kt
- mobile/src/androidTest/java/org/openhab/habdroid/ui/NfcTest.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
We shouldn't simply filter them, as doing so
- produces wrong visual output (no spacer)
- creates issues when visibility of that frame is changed
Instead, just hide the label and leave the spacer in place.
Fixes #1437
> Fix handling of frames without label.

- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
Creating the shared prefs instance is an operation that isn't trivial
(takes ~50ms on a OnePlus 6), so avoid doing it over and over again.
> Improve preference activity startup time

- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/res/layout/widget_item_update.xml
- mobile/src/main/res/layout/widget_item_update_small.xml
Directly after reboot the home screen widgets are not yet initialized, so the widgets show the openHAB icon and no item text. This PR replaces the view with a progress indicator.
> Show loading indicator in home screen widgets after reboot

- mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/WebViewFragment.kt
PR #105 introduced special code to jump to anchors after page load if
they were passed in the URL. As this both causes issues (fragment can
also be something that's not an anchor, see #1549) and seemingly isn't
needed anymore with newer WebView versions, remove that special
handling.
Fixes #1549
> Remove special anchor handling for WebViews.

- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
The night mode must be set after the migration.
> Fix migration to DayNight themes

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
removeView() changes the child count, so we need to remove the views
after iterating over them.
Fixes #1603
> Fix IndexOutOfBoundsException with section switch

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/values/strings.xml
"Light set to On" doesn't sound nice. This PR makes success toasts for a
few common states translatable. The success messages are not used for
NFC tags, because they are too long to be saved to the tag.
> Beautify success messages

- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml
- mobile/src/main/res/values/themes.xml
The new section switch implementation using MaterialButtonToggleGroup
(#1598) made the button much larger than they used to be, and moved the
highlight color from the secondary/accent color to the primary one.
Adjust styling of the buttons to roll back to previous behaviour in that
regard.
Fixes #1602
> Beautify section switch.

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
See https://community.openhab.org/t/android-app-beta/41382/145
> Ignore "com.android.providers.calendar" for alarm clock

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
Fixes #1638
See https://community.openhab.org/t/android-app-beta/41382/164
> Ignore "com.android.calendar" for alarm clock

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
The item update sent e.g. '45.0' as brightness, which then yielded a HSB state string
like '0,0,45.0', which we couldn't parse when getting it back. Fix the command sending
to send the (integer) progress instead, as this matches what we're doing when actually
binding the view.
Fixes #1658
> Fix slider behavior for color items.

- .github/workflows/labeler.yml
If it runs on pull request, the github token is not present and thus the action fails.
> Run labeler every 15 minutes

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/Constants.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/main/res/menu/left_drawer.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
The Sitemaps are hidden in the drawer by default, but there's a setting to change that.
See #392
Closes #1305
> Hide Sitemaps in drawer

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/util/Constants.kt
Instead of ignoring the alarm clock set by Tasker, send "0" to the
server. Also cache if the last sent alarm clock was 0 and don't send
again if so.
Fixes #1617
> Set alarm clock to 0 if alarm gets canceled

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
> Support DateTime items as Alarm clock receiver

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/DefaultConnectionTest.kt
This requires to bump the minApi to Android 5. I posted a topic about
that in September: https://community.openhab.org/t/raise-minimum-supported-android-version-to-android-5/82742
https://square.github.io/okhttp/upgrading_to_okhttp_4/
> Bump okhttp to 4.X

- mobile/src/main/res/values/strings.xml
The word "Status" can be understood as the current item status, not the
status the item is set to. "Action" is more clear.
Closes #1734
> Use "Action" instead of "Status" in ItemPicker

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/util/Constants.kt
`0` is actually a valid time stamp, so sent `UNDEF` instead.
Fixes #1737
> Send UNDEF instead of 0 if no alarm is active

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/res/drawable/ic_clear_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
Otherwise it's not possible to get rid of 404 errors if an item has been removed from the server, but the client still has a corresponding widget.
Also add a 404 error string for notifications.
> Add 'clear errors' action to background error notification

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
If only the default sitemap is shown in the drawer and the server
returns only one sitemap, the sitemap entry in the drawer isn't updated.
This can be reproduced by enabling demo mode.
> Update sitemap title in drawer if only one sitemap is returned

- mobile/src/main/java/de/duenndns/ssl/MemorizingTrustManager.java
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
Otherwise there's no error message if an SSL error occurs in background tasks.
> Use notification channels in MTM

- .github/workflows/build.yml
- .github/workflows/validate-strings.yml
v2 fetches only one commit by default:
https://github.com/actions/checkout/releases/tag/v2.0.0
> Update checkout action

- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
... and two lint fixes
````
Fatal Exception: java.net.BindException: Address already in use
at java.net.PlainDatagramSocketImpl.bind0(PlainDatagramSocketImpl.java)
at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:96)
at java.net.DatagramSocket.bind(DatagramSocket.java:390)
at java.net.MulticastSocket.<init>(MulticastSocket.java:172)
at java.net.MulticastSocket.<init>(MulticastSocket.java:137)
at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:464)
at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:423)
at javax.jmdns.JmDNS.create(JmDNS.java:99)
at org.openhab.habdroid.util.AsyncServiceResolver$resolve$2.invokeSuspend(AsyncServiceResolver.kt:80)
```` …
> Fix two crashes with JmDNS

- mobile/src/main/java/org/openhab/habdroid/util/MjpegInputStream.kt
````
Fatal Exception: java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
at java.util.Properties.loadConvert(Properties.java:573)
at java.util.Properties.load0(Properties.java:388)
at java.util.Properties.load(Properties.java:336)
at org.openhab.habdroid.util.MjpegInputStream.parseContentLength(MjpegInputStream.kt:54)
at org.openhab.habdroid.util.MjpegInputStream.readMjpegFrame(MjpegInputStream.kt:72)
at org.openhab.habdroid.util.MjpegStreamer$doStream$1.invokeSuspend(MjpegStreamer.kt:50)
````
> Fix "IllegalArgumentException: Malformed \uxxxx encoding."

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
Notifying the list fragment via callback only works for foreground
fragments, as background fragments will ask for (and receive) the widget
list via their onStart() -> ConnectionHandler.triggerUpdate(), which in
turn will send the last known widget list. This means we have to keep
that list up-to-date as well.
Closes #1779
> Correctly update widget list when updating widgets via SSE

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
~~For local (ethernet, Wi-Fi) networks it's very likely we don't need
internet connection for connecting to the (local) server, and for
cellular network we indirectly check for internet connection via the
validation flag.~~
In case one is connected to a Wifi network without internet connection,
and one has a working mobile network at that time, Android routes all
traffic through the mobile network. Since we want local connections to
actually be local, enforce those connections to be routed through the
network we determined the connection type from.
Closes #1633
> Bind local connections to their respective networks

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
Transport indicators aren't flags (bitmasks), but indices, so 0 is a
valid transport (and equals the CELLULAR transport), so we must not
filter it out.
> Fix remote connectivity on API level 26+

- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference
at org.openhab.habdroid.util.AsyncServiceResolver.getLocalIpv4Address(AsyncServiceResolver.kt:49)
at org.openhab.habdroid.util.AsyncServiceResolver.access$getLocalIpv4Address$p(AsyncServiceResolver.kt:32)
at org.openhab.habdroid.util.AsyncServiceResolver$resolve$2.invokeSuspend(AsyncServiceResolver.kt:82)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineSched …
```
> Fix NPE in AsyncServiceResolver

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
PR #1776 didn't help preventing this crash.
> Catch IllegalStateException when dispatching nfc

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
Instead of checking only the 'top priority' network for whether the
local connection is reachable, do that check for all networks that
might be local (Wifi, Ethernet, VPN) and only fall back to the remote
connection if that check fails for all of them.
Fixes #1804
> Refactor connection check logic.

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
We bind to networks only to ensure servers only reachable via one
network are connected via that network, we don't attach other properties
(e.g. desired security) to that bind request. If the binding operation
fails (e.g. because a VPN app installed a global VPN which prevents us
from using other networks), don't fail the socket creation due to that
failure.
Fixes #1804
> Be lenient about binding sockets to a given network.

- mobile/src/main/java/org/openhab/habdroid/core/connection/AbstractConnection.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/Connection.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
Instead of relying on the connection's socket factory for doing the
reachability check, pass the network to be used for the check directly
to the check method, which makes sure we aren't disturbing any ongoing
foreground operations on this connection while doing the check.
While at it, also move the checking code to DefaultConnection (it's only
needed for actual server connections, after all) and make the check
cancelable by using delay() instead of Thread.sleep().
Closes #1804
> Refactor server reachability check logic.

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/UrlInputPreference.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/test/java/org/openhab/habdroid/util/PreferencesUtilTest.kt
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.kt
It was possible to enter invalid urls like ´http:/example.com´.
> Instances of [HttpUrl] are well-formed and always have a scheme, host, and path. With
> `java.net.URL` it's possible to create an awkward URL like `http:/` with scheme and path but no
> hostname. Building APIs that consume such malformed values is difficult!
from HttpUrl.kt docs
Fixes #1825
> Fix url validation in UrlInputPreference

- docs/USAGE.md
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/PeriodicItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/drawable/ic_battery_off_outline_grey_24dp.xml
- mobile/src/main/res/drawable/ic_battery_outline_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
Periodic workers don't have a failed state, so the notification listener
doesn't know if the job has failed or not. Because of that I used a
periodic worker for triggering a one time worker that sends the battery
level.
While charging the frequency is lowered to 10 - 15 minutes, if the
battery isn't low.
Closes #269
> Send battery level to server

- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/res/values/strings.xml
The default severity channel is now created by default. Otherwise the
"Other" group wouldn't make much sense.
> Add notification channel groups

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/foss/res/layout/widgetlist_mapitem.xml
- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/res/layout/widgetlist_mapitem.xml
- mobile/src/main/java/org/openhab/habdroid/core/connection/Connection.kt
- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/AutoHeightVideoView.kt
- mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/drawable/ic_data_usage_black_48dp.xml
- mobile/src/main/res/layout/widgetlist_chartitem.xml
- mobile/src/main/res/layout/widgetlist_data_saver.xml
- mobile/src/main/res/layout/widgetlist_imageitem.xml
- mobile/src/main/res/layout/widgetlist_videoitem.xml
- mobile/src/main/res/layout/widgetlist_videomjpegitem.xml
- mobile/src/main/res/layout/widgetlist_webitem.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
- mobile/src/test/java/org/openhab/habdroid/model/SitemapTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
Respect device wide data saver and add setting to enable data saver for
openHAB only.
If enabled, ...
* widgets with high data usage are replaced by a button that shows them
* automatic image refresh is disabled
* icon paths don't contain the state => reduces icon downloads
* chart resolution is lowered
Fixes #660
> Implement data saver

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
````
Caused by kotlin.KotlinNullPointerException
at org.openhab.habdroid.ui.ChartActivity.onCreate(ChartActivity.kt:51)
at android.app.Activity.performCreate(Activity.java:7981)
````
> Fix NPE in ChartActivity

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
Add some fixes that didn't make it in time for #1897:
- Don't recreate activity on missing permission, instead disable the
respective prefs directly
- Use more Kotlinesque language constructs
> Clean up WiFi SSID sending code.

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
The docs of getApplicationInfo() say that it returns non-null, but sometime the following crash happens:
````
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.ApplicationInfo.enabled' on a null object reference
at org.openhab.habdroid.ui.PreferencesActivity.isAutomationAppInstalled(PreferencesActivity.kt:519)
at org.openhab.habdroid.ui.PreferencesActivity.onCreatePreferences(PreferencesActivity.kt:310)
at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
````
> Fix NPE in isAutomationAppInstalled()

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
I noticed the state may appear in the data saver hint for charts with a single item. Since this has been an issue in the past (#1912), I decided to remove the state completely from `label` and only show it when we really want to show it.
> Only show state in label where explicitly wanted

- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Especially for testing it's useful to force the app to do periodic background work. This is a nice way to do so and device and radio are already awake.
> Run periodic work on application start

- mobile/src/main/res/values/strings.xml
"Alarm time" is better English than "Alarm clock time"
> Improve device info strings

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/layout/widgetlist_videoitem.xml
* Hide loading indicator if data saver hint is shown
* Start video after clicking on "Load anyway"
> Video widget: Data saver improvements

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/res/values/strings.xml
````
Fatal Exception: java.lang.RuntimeException: Failure from system
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1719)
at android.app.Activity.startActivityForResult(Activity.java:5252)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
at android.app.Activity.startActivityForResult(Activity.java:5203)
at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
at android.app.Activity.startActivity(Activity.java:5581)
at android.app.Activity.startActivity(Activity.java:5549)
at org.openhab.habdroid.ui.LogActivity$onCreate$1.onClick(LogActivity.kt:67)
...
Caused by android.os.TransactionTooLargeException: data parcel size 1169344 bytes
at …
```
> Fix crash when log is too large to share

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/res/layout/activity_main.xml
> ContentLoadingProgressBar implements a ProgressBar that waits a minimum time to be
> dismissed before showing. Once visible, the progress bar will be visible for
> a minimum amount of time to avoid "flashes" in the UI when an event could take
> a largely variable time to complete (from none, to a user perceivable amount)
from the Java docs of ContentLoadingProgressBar.
> Avoid flashing progress indicator in action bar

- mobile/build.gradle
Reverts openhab/openhab-android#2017
I see a new crash since security-crypto has been bumped to 1.0.0-rc02:
````
Fatal Exception: java.lang.SecurityException: Could not decrypt value. decryption failed
at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:546)
at androidx.security.crypto.EncryptedSharedPreferences.getString(EncryptedSharedPreferences.java:377)
at org.openhab.habdroid.util.PrefExtensionsKt.getStringOrNull(PrefExtensions.kt:124)
at org.openhab.habdroid.core.connection.ConnectionFactory.makeConnection(ConnectionFactory.kt:302)
at org.openhab.habdroid.core.connection.ConnectionFactory.updateConnections(ConnectionFactory.kt:173)
at org.openhab.habdroid.core.connection.ConnectionFactory$Companion$initialize$1.invokeSuspend(Conn …
```
> Revert "Bump security-crypto from 1.0.0-rc01 to 1.0.0-rc02"

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
The DND mode pref isn't shown there
> Fix crash on Android L when changing prefix

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
````
Fatal Exception: java.util.concurrent.CancellationException: Task was cancelled.
at androidx.media2.player.futures.AbstractResolvableFuture.cancellationExceptionWithCause(AbstractResolvableFuture.java:1193)
at androidx.media2.player.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:515)
at androidx.media2.player.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:476)
at org.openhab.habdroid.ui.WidgetAdapter$VideoViewHolder$bindAfterDataSaverCheck$1.run(WidgetAdapter.kt:970)
at android.os.Handler.handleCallback(Handler.java:883)
````
> Fix crash in Video item

- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
There are several places where trailing whitespaces don't look nice, e.g. in NFC success toasts.
> Trim Item and Widget labels

- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt
Once FCM registration was successful, we aren't interested in previous
exceptions anymore. When keeping them, we continue reporting failure
even though registration was successful.
> Correctly reset FCM registration failure.

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Listen for events of schedule bases items when the app is in the foreground. This applies to all Android versions.
See #2014
> Listen for schedule based item events when in foreground

- docs/USAGE.md
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/core/VoiceService.kt
- mobile/src/main/java/org/openhab/habdroid/model/NfcTag.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemUpdateWidgetItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/NfcItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/DeviceIdentifierPreference.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/ItemUpdatingPreference.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
- mobile/src/main/java/org/openhab/habdroid/util/Util.kt
- mobile/src/main/res/drawable/ic_tag_text_outline_grey_24dp.xml
- mobile/src/main/res/layout/pref_dialog_device_identifier.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences.xml
- mobile/src/main/res/xml/preferences_device_information.xml
Rename the existing prefix of "Send device info" to "Device identifier"
and make it available for NFC tags and voice command.
Closes #1692
Closes #1951
For NFC tags a new query parameter is added (`d=true`) if the device
identifier should be send instead of the state on the tag. Older clients
will send "UNSUPPORTED" instead.
> Replace item prefix with device identifier

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
> Example use-cases for this new feature include [...] a task that's important to the user of the app.
https://developer.android.com/topic/libraries/architecture/workmanager/advanced/long-running
Especially item updates done by NFC tags or widgets are important enough
to start a foreground service.
~~Maybe the input data should signal the worker if it's important or not. The last retry should always be treated as important, as well as when the user manually retries any failed workers.
Though in this case the previous "Items are currently being updated" would be shown.~~
> WorkManager: Use foreground service for item updates

- mobile/src/main/AndroidManifest.xml
Fixes https://issuetracker.google.com/issues/147873061
> Specify WorkManager foreground service type in Manifest

- mobile/src/main/java/org/openhab/habdroid/ui/preference/DeviceIdentifierPreference.kt
Load the set value to correctly initialize the preference.
> Fix device id preference

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/model/NfcTag.kt
````
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openhab.habdroid/org.openhab.habdroid.background.NfcReceiveActivity}: java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
at android.os.Handler.dispatchMessage(Handler.java:107)
at …
```
> Fix crash when reading invalid NFC tag

- mobile/src/main/AndroidManifest.xml
- mobile/src/main/res/values-night/themes.xml
- mobile/src/main/res/values/themes.xml
When the app is launched, the status bar is now white or black, based on
the day/night theme. After the MainActivity is loaded, the status bar
color is changed according to the configured theme.
Previously it was always orange during startup.
This change only applies to Android 10.
> Improve launch theme

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/NfcItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/TaskerItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
E.g. when sending a string to a switch Item.
> Hide dev id as state option if it would produce errors

- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
Before the generic message "Item has been set to ON" was used
instead of the "on" message: "Item has been turned on".
This happened only for TOGGLE on switch items.
> Improve success toast for toggle on switches

- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
NotificationHelper needs a fully initialized context, which in the case
of a Service means attach() was called, which in turn happens between
constructor and onCreate() invocation.
Closes #2044
> Fix crash when FcmMessageListenerService is started.

- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
We already avoided the cache for the actual refresh, but not for the
initial load triggered via onAttachedToWindow(). Since we need the
information whether refresh is enabled in that method, but the actual
sequence of calls is setImageUrl() -> onAttachedToWindow() ->
startRefreshing(), move the refresh interval setter to setImageUrl(), so
we have the interval available in onAttachedToWindow().
Closes #2066
> Always avoid cache when loading images that have refresh set.

- docs/USAGE.md
- mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
- mobile/src/main/res/layout/widgetlist_icontext.xml
- mobile/src/main/res/layout/widgetlist_imageitem.xml
- mobile/src/main/res/values/dimens.xml
In particular, fix rendering of SVGs with explicit sizes and of
non-square SVGs.
Closes #2021
Closes #913
> Fix up SVG rendering.

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
We might show multiple snackbars on launch, e.g. "Connected to local
server" and a warning that the app doesn't have the permissions for all
active background tasks.
Instead of hiding the previous snackbar when showing a new one, queue
the new one.
> Queue snackbars instead of hiding the previous one

- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
I checked a few devices and each one had its own bitmap size limits,
so I implemented this dynamic approach.
Fixes #2053
> Scale down image used in widgets

- mobile/src/main/java/org/openhab/habdroid/background/BroadcastEventListenerService.kt
````
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7c9a704 u0 org.openhab.habdroid.beta/org.openhab.habdroid.background.BroadcastEventListenerService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2010)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7643)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
````
> Fix crash in event listener

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
When connecting the first time to a new server or after clearing the default sitemap,
a sitemap is automatically selected, if it's the only one.
`updateDefaultSitemap()` was called, but before saving the default
sitemap to prefs, `updateSitemapAndHabPanelDrawerItems()` was called and
changed the drawer state to "no default sitemap selected".
Fix this by moving `updateSitemapAndHabPanelDrawerItems()` out of
`prefs.edit{}`.
> Display correct sitemap name in drawer

- mobile/src/main/res/layout/widgetlist_videoitem.xml
With this commit the widget list is less "jumping" around when the video widget
changes between loading and error or showing.
> Increase size of video error hint

- .idea/codeStyles/Project.xml
Sticker error:
> Imports must be ordered in lexicographic order without any empty lines in-between
> Specify correct import order in .idea

- mobile/build.gradle
- mobile/google-services.json
- mobile/src/foss/java/org/openhab/habdroid/util/RemoteLog.kt
- mobile/src/full/AndroidManifest.xml
- mobile/src/full/java/org/openhab/habdroid/util/RemoteLog.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
Fixes #2179
Disable crash reporting for builds older than 6 months and debug builds.
Fixes #564
> Upgrade to the Firebase Crashlytics SDK

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
https://community.openhab.org/t/not-always-lines-under-items-on-sitemap-openhab-app/103961
> Fix divider not showing when there're invible widgets

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerOnePane.kt
````
Fatal Exception: java.lang.IllegalStateException: FragmentManager has been destroyed
at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1737)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
at org.openhab.habdroid.ui.activity.ContentControllerOnePane.executeStateUpdate$mobile_fullStableRelease(ContentControllerOnePane.kt:50)
at org.openhab.habdroid.ui.activity.ContentController.updateFragmentState(ContentController.kt:459)
at org.openhab.habdroid.ui.activity.ContentController.clearServerCommunicationFailure(ContentController.kt:314)
at org.openhab.habdroid.ui.MainActivity.retryServerPropertyQuery(MainActivity.kt:525)
at …
```
> Fix crash "FragmentManager has been destroyed"

- mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/values/strings.xml
Fixes #1898
Also avoid auto playing videos when data saver is on and the app is whitelisted.
> Conversely, to work well with Data Saver, apps should not: [...] Treat whitelisting as a license to use more bandwidth
https://source.android.com/devices/tech/connect/data-saver?hl=en
> Support battery saver

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerOnePane.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentControllerTwoPane.kt
Instead of taking the saved state from the activity, use it from the
fragment manager itself.
From the Java docs of `isStateSaved()`:
> Any operations that would change saved state should not be performed if this method returns true. For example, [...] any FragmentTransaction using {@link FragmentTransaction#commit()} instead of {@link FragmentTransaction#commitAllowingStateLoss()} will change the state and will result in an error.
Fixes #1650
> Fix fragement manager IllegalStateException

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
When creating a new server the inital config is a ServerConfiguration with empty or null values. The equal check with the server config from prefs always fails, because `null` is saved.
> Only show confirm leave dialog if the config was changed

- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/res/values/strings.xml
This channel group isn't required, because Android puts notifications under
"Other" if no group is set.
> Remove channel group "Other"

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
This code isn't executed for Android < M, because the pref is hidden.
> Fix lint regarding DND mode and min sdk

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
````
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.snackbar.Snackbar.show()' on a null object reference
at org.openhab.habdroid.ui.AbstractBaseActivity$showSnackbar$1.invoke(AbstractBaseActivity.kt:170)
at org.openhab.habdroid.ui.AbstractBaseActivity.showSnackbar(AbstractBaseActivity.kt:197)
at org.openhab.habdroid.ui.AbstractBaseActivity.showSnackbar$default(AbstractBaseActivity.kt:162)
at org.openhab.habdroid.ui.MainActivity.showPushNotificationWarningIfNeeded(MainActivity.kt:1072)
at org.openhab.habdroid.ui.MainActivity$showPushNotificationWarningIfNeeded$1.invokeSuspend(:11)
at …
```
> Fix snackbar related crashes

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
SSE failures of the sitemap don't impair the refresh of HABPanel.
> Hide SSE failure snackbar when opening HABPanel

- mobile/src/main/java/org/openhab/habdroid/ui/preference/CustomInputTypePreference.kt
````
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property whitespaceBehavior has not been initialized
at org.openhab.habdroid.ui.preference.CustomInputTypePreference$PrefFragment.afterTextChanged(CustomInputTypePreference.kt:130)
at android.widget.TextView.sendAfterTextChanged(TextView.java:11664)
at android.widget.TextView.setText(TextView.java:6851)
at android.widget.TextView.setText(TextView.java:6642)
at android.widget.EditText.setText(EditText.java:140)
at android.widget.TextView.setText(TextView.java:6594)
at android.widget.TextView.setTransformationMethod(TextView.java:2870)
at android.widget.TextView.setInputType(TextView.java:7100)
at org.openhab.habdroid.ui.preference.CustomInputTypePreference$PrefFragment.onBindDialogView(CustomInputTypePreference.kt:9 …
```
> Fix UninitializedPropertyAccessException in CustomInputTypePreference

- .idea/dictionaries/openhab.xml
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences_server.xml
An optional Wi-Fi SSID can be configured for each server. If the app is
started and connected to one of these Wi-Fis, it switches to the
corresponding server.
Later this preference could be used force connecting to a remote url,
see #146.
Closes #2229
> Auto select server based on Wi-Fi SSID

- mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
An empty string is even a suggested command for StringItems.
> Allow empty strings as tile state

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/NotificationUpdateObserver.kt
- mobile/src/main/java/org/openhab/habdroid/background/tiles/AbstractTileService.kt
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
If the item update cannot be sent directly after the click on the tile, the tile service is most likely killed, before the update was successful/failed. Therefore the subtitle shows "Waiting..." until the user clicks on the tile again.
> Make sure that tile subtitle is updated

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Increase the hitbox from the arrow only to the complete header, like it's done for switches in the settings.
> Increase server selector hitbox

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
When entering the tile prefs via long pressing the tile, it didn't close
on save.
> Make sure tile prefs is always closed after saving

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/res/values/strings.xml
Sometimes it's useful to quickly get the name of an Item, e.g. when configuring quick tiles or Tasker. This new long press action also allows some code cleanup, because "Create widget" now never appears as the only action.
> Add long press action to copy item name

- mobile/src/full/res/values/strings.xml
- mobile/src/main/res/values/strings.xml
* Put "notification" in every string, so it isn't out of context when
shown as Snackbar in MainActivity
* Remove FCM from the success string, because it's quite technical
> Improve notification status strings

- README.md
* Dependabot shows "Inactive", because we're using the native Dependabot now.
* lgtm doesn't support Kotlin and isn't able to build the Java part currently.
> Remove some badges from Readme

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
IMO all TODOs and FIXME should be tracked as GitHub issue, so the TODO
tab in AS can be used for WIP PRs.
The icon here is fine for me, so I just remove the FIXME.
> Remove FIXME in code

- CONTRIBUTING.md
- README.md
- docs/USAGE.md
- mobile/src/beta/res/values/strings.xml
- mobile/src/full/res/values/strings.xml
- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/res/values/strings.xml
The default branch has been renamed to main in most openHAB repos.
> Update links after branch rename

- mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
If the user name is longer than 50 chars, assume it's an API token and therefore no password is required.
The keys I generated where usually 82 chars long, but they might be shorter and 50 is longer than the most mail addresses.
> Don't show authenticated connections as insecure

- .github/workflows/build.yml
- .github/workflows/validate-strings.yml
For the branches l10n_main and dependabot/* there's always an open PR, so the CI runs twice: For push and for pull_request.
> Avoid duplicate CI runs

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
Fixes #2412
Closes #2417
IMO this is a better solution than in #2417, because it doesn't require to add the actions to the manifest.
> Fix issue with package visibility

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
The `OnPreferenceChangeListener` was overridden, so the permission was
never requested.
> Fix permission request for 'Send ssid'

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
They're always the same colors and probably will be in future use cases
as well.
> Remove arguments from SwipeRefreshLayout.applyColors()

- mobile/src/main/res/layout/activity_about.xml
- mobile/src/main/res/layout/activity_chart.xml
- mobile/src/main/res/layout/activity_item_picker.xml
- mobile/src/main/res/layout/activity_log.xml
- mobile/src/main/res/layout/activity_main.xml
- mobile/src/main/res/layout/activity_prefs.xml
- mobile/src/main/res/layout/activity_writetag.xml
Fixes `AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.`
> Fix app:theme deprecation

- mobile/src/main/java/org/openhab/habdroid/ui/preference/BetaPreference.kt
- mobile/src/main/res/drawable/rounded_corner_box.xml
Now the border of the "beta" text changes when enabled/disabled.
> Improve beta pref background when disabled

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
This adds an auto generated `toString()` function. The current one
returns e.g. `org.openhab.habdroid.model.IconResource@ae3c432`.
> Make IconResource a data class

- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
"Important" work is usually triggered by an action of the user.
When I tap on a quick tile, e.g. `TOGGLE` light, and the connection cannot be established, I use the wall switch to turn it on. Then the 7th or so retry succeeds and `TOGGLE`s the light of again.
With this PR the error is shown faster to avoid such behavior.
> Reduce retry count for important work

- mobile/src/main/res/layout/chart_scaling_pref.xml
I noticed that the summary is truncated on small displays when the font is set to large.
> Always show full chart scalling summary

- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
````
Fatal Exception: java.lang.UnsupportedOperationException: Exceeded maximum number of wifi locks
at android.net.wifi.WifiManager$MulticastLock.acquire(WifiManager.java:3370)
at org.openhab.habdroid.util.AsyncServiceResolver.resolve(AsyncServiceResolver.kt:77)
at org.openhab.habdroid.ui.MainActivity$onActiveConnectionChanged$1.invokeSuspend(MainActivity.kt:476)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
````
> Catch "Exceeded maximum number of wifi locks" during discovery

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
````
Fatal Exception: java.lang.IllegalArgumentException: Max number of dynamic shortcuts exceeded
at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
at android.os.Parcel.createException(Parcel.java:2357)
at android.os.Parcel.readException(Parcel.java:2340)
at android.os.Parcel.readException(Parcel.java:2282)
at android.content.pm.IShortcutService$Stub$Proxy.addDynamicShortcuts(IShortcutService.java:703)
at android.content.pm.ShortcutManager.addDynamicShortcuts(ShortcutManager.java:232)
at org.openhab.habdroid.ui.MainActivity.manageShortcut(MainActivity.kt:1365)
at org.openhab.habdroid.ui.MainActivity.manageHabPanelShortcut(MainActivity.kt:1328)
at org.openhab.habdroid.ui.MainActivity.updateDrawerItemVisibility(MainActivity.kt:968)
at …
```
> Fix IllegalArgumentException when adding shortcut

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
Don't hardcode it to 0, since they might be invisible widgets at the top
of the list.
Fixes #2455
> Determine actual position of first visible widget

- mobile/src/main/java/org/openhab/habdroid/model/WebViewUi.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/HabpanelWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/Oh3UiWebViewFragment.kt
IMO this makes it easier to
1. pass arguments to the fragment, like `callback`
2. implement #2289 and #2337
> Use child classes of WebViewFragment for each UI

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
The discovery is started in the intro and MainActivity, but only if no server is configured.
However the second discovery can be started before the first one finds a
server. Then both runs may add a server to the prefs.
> Avoid adding two servers during discovery

- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
Fixes #2220
`PageConnectionHolderFragment`'s `connections` was null after it has
been recreated.
> Load widgets after activity has been restored

- .github/workflows/build.yml
Recently gradle throws OOM exceptions quite often.
The default runner has 7GB ram: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
> Increase memory allocated by JVM

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/LockableDrawerLayout.kt
- mobile/src/main/res/layout/activity_main.xml
When the app is opened by a shortcut to e.g. HABPanel, and it doesn't go
fullscreen, the drawer button is disabled as well.
With this commit only disable swipe-to-open, but keep the drawer button
active.
> Only lock swipe on drawer

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
Now the user can see if the log is complete since it was manually cleared.
> Log when log was cleared

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
In the following case a divider was falsely drawn:
````
Frame {
Hidden widget
Divider
Hidden widget
Shown widget
}
````
Fixes #2378
> Fix widget dividers not hidden

- mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/HabpanelWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/Oh3UiWebViewFragment.kt
Frontail doesn't have a drawer on its own, so no need to lock the app drawer here.
> Only lock drawer for webview UIs with side menu

- mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
Fixes #2506
````
W/WebView: java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {44709f2} called on Looper (JavaBridge, tid 6438) {7566e81}, FYI main Looper is Looper (main, tid 2) {44709f2})
at android.webkit.WebView.checkThread(WebView.java:2575)
at android.webkit.WebView.getUrl(WebView.java:1251)
at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.getShortcutInfo(AbstractWebViewFragment.kt:96)
at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.pinShortcut(AbstractWebViewFragment.kt:206)
at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.access$pinShortcut(AbstractWebViewFragment.kt:70)
at org.openhab.habdroid.ui.activity.AbstractWebViewFragment$OHAp …
```
> Fix creation of webview shortcuts

- mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
The following cell didn't work for me at all in the app:
````
- component: oh-cell
config:
action: url
actionUrl: https://github.com/openhab/openhab-android
title: GitHub
style:
loading: lazy
````
Fixes #2504
> Fix opening URLs in main UI

- mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
- mobile/src/main/res/layout/fragment_webview.xml
The current progress indicator is shown in the middle of the screen. It
may draw on top of Webview content, because the indicator is hidden at
100% loading progress. However some content may be displayed before,
e.g. at 70%.
> Use a progress bar in WebViews

- mobile/src/main/AndroidManifest.xml
`SpeechRecognizer.isRecognitionAvailable()` internally uses a query
which has to be added to the manifest to work on Android 11.
> Fix voice widget not available

- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
If `WidgetImageView` is used for a URL image with refresh and then
recycled for a base64 image without refresh, so previous refresh isn't
stopped.
Fixes #2539
> Fix base64 images overridden by URL images

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
Otherwise causes:
````
Fatal Exception: java.lang.IllegalStateException: Fragment SendDeviceInfoSettingsFragment not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
at org.openhab.habdroid.ui.PreferencesActivity$SendDeviceInfoSettingsFragment.onSharedPreferenceChanged(PreferencesActivity.kt:1148)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:612)
at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:494)
at androidx.preference.Preference.tryCommit(Preference.java:1632)
at androidx.preference.Preference.persistString(Preference.java:1663)
at org.openhab.habdroid.ui.preference.ItemUpdatingPreference.setValue(ItemUpdatingPreference.kt:109)
at …
```
> SendDeviceInfoSettingsFragment: Unregister shared prefs listener

- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
It's always `String`, never `String?`.
> Fix return value of Location.toMapsUrl()

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/res/drawable/ic_keyboard_arrow_down_grey_24dp.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences_server.xml
IMO there are more users that are confused by this settings, then
actual users of this. I added an entry "Advanced" that shows the
client cert and wifi prefs when clicked.
The Android settings have the same feature: Under "Network and Internet"
a few preferences are hidden by default, e.g. VPN or DoH.
> Hide client cert pref by default

- mobile/build.gradle
Use BoM to keep all Firebase libs compatible. This BoM has
firebase-messaging at version 20.3.0.
In later versions I haven't found a way to pass `CloudConnection.messagingSenderId` to the token getter.
> Bump several Google dependencies

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
Previously `null` as widget label meant that the label will be generated
automatically based on the item label and item command during widget
update.
Now this is done when selecting an item and command in the
PreferencesActivity.
Fixes #2603
> Migrate widget label

- mobile/src/main/java/org/openhab/habdroid/ui/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/SslClientCertificatePreference.kt
`onSetInitialValue()` calls `getPersistedString()`, but
SslClientCertificatePreference isn't persistent and therefore always
loads the default value, which is `null`.
This resulted in a loss of the cert whenever the server prefs have been
saved.
Fixes #2566
> Fix SslClientCertificatePreference persistence

- mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt
> Fix crash when shortcut title is empty

- mobile/src/main/AndroidManifest.xml
SystemForegroundService implements LifecycleService which implements
Service. However Android Studio isn't able to resolve LifecycleService
and therefore throws an error.
> Suppress manifest error for SystemForegroundService

- mobile/src/main/java/org/openhab/habdroid/ui/preference/CustomInputTypePreference.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/WifiSsidInputPreference.kt
- mobile/src/main/res/xml/preferences_server.xml
TODO:
It seems that there's no way to get all saved Wi-Fi SSIDs on the latest Android version. Therefore only suggest the current one.
In most cases the user will be connected to the correct Wi-Fi when setting up the server anyway.
Closes #2663
> Suggest SSIDs in Settings

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
`notifyDataSetChanged()` is only used when updating single items isn't
possible, e.g. number of items changed.
> Reduce lint warnings in WidgetAdapter

- mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
A few devices have the following crash, so it seems that the migration didn't run there.
````
Fatal Exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set
at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:298)
at org.openhab.habdroid.model.ServerConfiguration$Companion.load(ServerConfiguration.kt:173)
at org.openhab.habdroid.core.connection.ConnectionFactory.loadServerConnections(ConnectionFactory.kt:221)
at org.openhab.habdroid.core.connection.ConnectionFactory.updateConnections(ConnectionFactory.kt:206)
at org.openhab.habdroid.core.connection.ConnectionFactory.updateConnections$default(ConnectionFactory.kt:193)
at org.openhab.habdroid.core.connection.ConnectionFactory$Companion$initialize$1.invokeSuspend(ConnectionFactory.kt:5 …
```
> Fix ClassCastException when loading server configuration

- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
openHAB 3 returns `Switch` as default icon for switch items. Therefore
the icon suggestion for quick tiles fails, because `"Switch" != "switch"`.
Because the icon rest api also works case insensitive, force lower case
on all icon names of items.
Example:
- https://demo.openhab.org/icon/bedroom_blue
- https://demo.openhab.org/icon/BedRoom_blue
Both links show the same icon.
> Case insensitive icon name handling

- build.gradle
- mobile/build.gradle
- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationWorker.kt
- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/AsyncServiceResolver.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
Workers have to implement `getForegroundInfoAsync()` on Android < 12 or
they will crash.
Solution taken from https://stackoverflow.com/a/69627331
Fixes #2761
> Fix ItemUpdateWorker crash on Android < 12

- mobile/src/main/res/values/strings.xml
* Present tense instead of simple past
* 'Side menu' instead of 'Sitemap drawer': Same wording than in the settings
> Improve drawer accessibility strings

- mobile/build.gradle
This version requires some migrations, see #2799
This reverts commit db5853cf0ff64a8bcd2a4a9a569762ab8a878993.
> Revert "Bump material from 1.4.0 to 1.5.0 (#2797)"

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
This helps in two cases:
1. The user clicks on the 'Failed to update item' notification. In this
case the notification and therefore also the notification action
'retry' vanishes. Then the user cannot retry sending e.g. the alarm
clock.
2. Existing 'waiting for network' workers are queued again and will
send the update immediatly.
> Trigger all 'Send device info' workers when opening app

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
This listener is also used for `secretPrefs`. However the active server
ID isn't saved there and therefore `getActiveServerId()` always returns
the default value `0`.
This leads to not updating connections when changing credentials.
> Lookup active server ID in correct shared prefs

- docs/USAGE.md
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Fixes https://github.com/openhab/openhab-android/issues/2887
I added the link to the Google app to the docs, because the "No voice recognition app found" snackbar will probably not show up anymore.
> Hide microphone icon when voice recognizer is unavailable

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
When the permissions for location access isn't granted, the background tasks silently fail.
> Request location background permissions

- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
Background: I was looking at a way to hide "internal" items from Android
11 device control, e.g. items used to synchronize between rules or store
rule states.
I discovered that Items without a label are filtered out, but this only
works when the label can be actually null/empty.
> Don't fallback to Item name as label

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/EventListenerService.kt
- mobile/src/main/res/xml/preferences_device_information.xml
See https://github.com/openhab/openhab-android/issues/2895#issuecomment-1133591328
There's an exeception for bluetooth related broadcasts: https://developer.android.com/guide/components/broadcast-exceptions.html
> Make sending bluetooth device addresses event based

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
icon="" should be treated the same way as icon="none" or omitting icon
altogether.
> Fix empty icon handling.

- mobile/src/main/res/values/strings.xml
* Add context to all strings with more than one placeholder
* Write some terms with a capital first letter
Fixes #2972
> Improve strings

- mobile/build.gradle
- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
Make the service implementation use coroutines, and convert SSE handling to coroutines as well.
Additionally, refactor device control creation to happen from a factory object which encapsulates all information required in the creation process.
> Clean up / simplify device controls service

- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
- Make data transfer policy depend on whether the used connection is
metered or not, and only apply data saver logic on metered connections
- Make sure battery saver does not override data saver constraints
- Remove unneeded NetworkTypeApiHelper variants; all needed APIs are
available in API 21 and newer
> Refactor data saver handling

- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
> Item control: Don't print an error for ALIVE events

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
When two icons with custom state `null` and `""` (empty string) are compared, `equals()` returns `false`.
Since there's no semantic difference between an icon with state `null`
or `""`, make `customState` non-nullable.
Fixes #2985
> Fix comparing equal icon resources

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
See #3010
Needs to be rebased on #3014
> Add workaround for alarm time on Android 13

- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/PeriodicItemUpdateWorker.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
* Add a function to do several kind of periodic work: `doPeriodicWork()`
* Call `doPeriodicWork()` instead of `BackgroundTasksManager.triggerPeriodicWork()` and `ItemUpdateWidget.updateAllWidgets()`
With this change notifications are polled when starting the app.
> Improve execution of periodic work

- mobile/src/main/res/layout/widgetlist_frameitem.xml
Compared to other text sizes the frame label was quite small.
In Basic UI the frame label is also larger than the labels of other items.
> Increase frame label

- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
Sliders require values to be Floats, so I changed
Item.minimum/maximum/step to Float.
> Fallback to min/max/step of Item if not set for Widget

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/BasicItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/SuggestedCommandsFactory.kt
The item state can be displayed this way.
> Show read-only items in widget item picker

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
> Don't pass ServerProperties to AboutActivity

- mobile/src/main/res/layout/widgetlist_coloritem.xml
Color widgets are the only widgets that don't show there state directly in the Sitemap. There's enough space to display a value and IMO it's a good addition.
Server-side I'm using the JS map to get the brightness in percent from the item state.
> Display item states in color items

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int[] android.appwidget.AppWidgetManager.getAppWidgetIds(android.content.ComponentName)' on a null object reference
at org.openhab.habdroid.background.BackgroundTasksManager$Companion.schedulePeriodicTrigger(BackgroundTasksManager.kt:457)
at org.openhab.habdroid.background.BackgroundTasksManager$Companion.schedulePeriodicTrigger$default(BackgroundTasksManager.kt:450)
at org.openhab.habdroid.background.BackgroundTasksManager$Companion.scheduleWorker(BackgroundTasksManager.kt:542)
at org.openhab.habdroid.background.BackgroundTasksManager$Companion.scheduleWorker$default(BackgroundTasksManager.kt:533)
at org.openhab.habdroid.background.BackgroundTasksManager.onReceive(BackgroundTasksManager.kt:134)
at …
```
> Fix crash when scheduling periodic trigger

- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
For #3143 I set the label of an Item to `Color [JS(hsb-to-brightness.js):%s]`. When this Item is fetched via /rest/items/ the brackets aren't resolved to the actual value. When fetched via /rest/sitemaps/ the brackets are placed. Since `[JS(hsb-to-brightness.js):%s]` isn't useful to be shown in the device control, I added a splitting of the label as it's done for Widgets.
> Remove state from Item label

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
Those have an implicit range of 0..100, because they're fed with PercentageType values.
Fixes #3194
> Do not use item min/max values for dimmer sliders

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
https://community.openhab.org/t/alarm-clock-andorid-sends-undef/133718/19
> Ignore alarm from com.miui.securitycenter

- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
````
kotlin.UninitializedPropertyAccessException: lateinit property searchView has not been initialized
at org.openhab.habdroid.ui.LogActivity$fetchLog$1.invokeSuspend(LogActivity.kt:186)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:7664)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
````
````
Fatal Exception: …
```
> Fix two crashes with search view in log

- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
One of our base themes must be set even when using dynamic colors to make our custom attributes work.
Fixes #3214
> Apply dynamic theme correctly

- mobile/src/main/res/values/styles.xml
In compact mode the line height is at least `48dp` high, so no additional scrolling is required after this change.
Closes #3158
> Fix touch target size warnings

- .github/ISSUE_TEMPLATE/release.yml
When the beta version is downloaded from GitHub manually, crashes are sent to Firebase.
> Check for crashes in beta before publishing

- mobile/src/main/res/layout/widgetlist_switchitem.xml
- mobile/src/main/res/layout/widgetlist_switchitem_compact.xml
Keep the old one in dialogs in the settings to have a consistent look in PreferencesActivity.
> Use the new MaterialSwitch instead of SwitchMaterial

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
NET_CAPABILITY_VALIDATED was introduced in API 23, so don't check for it in lower API levels
> Fix mobile network detection on API < 23

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/layout/widgetlist_sectionswitchitem.xml
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_compact.xml
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_overflow_button.xml
- mobile/src/main/res/values-w450dp/dimens.xml
- mobile/src/main/res/values-w750dp/dimens.xml
- mobile/src/main/res/values/dimens.xml
- Only assign needed width to overflow button
- Allow more buttons to be shown on large tablets
Fixes #3238
> Improve section switch overflow handling

- mobile/src/main/AndroidManifest.xml
Otherwise the newly introduced permissions imply that these hardware features are required.
> Declare camera and mic as optional hardware

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
This makes sure changes to this setting become effective immediately and do not require an app restart.
Fixes #3273
> Apply 'Keep screen on' setting not only on activity creation

- mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
The keyword `currentColor` can be used to color SVGs. This seems to be the best solution for the "colorless" icon issue.
Closes #3204
> Color SVG icons

- mobile/src/main/java/org/openhab/habdroid/ui/AboutActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ColorItemActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/SelectionItemActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/layout/activity_color_picker.xml
- mobile/src/main/res/layout/activity_main.xml
- mobile/src/main/res/layout/activity_selection_item.xml
- mobile/src/main/res/layout/app_bar.xml
Fix cases where padding wasn't correct with or without fullscreen mode on some API levels.
While at it, also replace some related deprecated code and deduplicate toolbar handling.
> Refactor window insets handling

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
If the item state is `null`, the overflow button is checked as its tag is also `null`.
> Don't check overflow button

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
Signal uses AlarmManager for scheduled messages, which are no real alarms.
> Ignore alarms set by Signal

- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/FrontailWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ServerEditorFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences_drawer_entries.xml
- mobile/src/main/res/xml/preferences_server.xml
I implemented it this way so users can not only change port, but also scheme and/or host. It also allows us to re-use existing code, e.g. UrlInputPreference.
Closes #3260
> Allow custom Frontail URL

- .idea/compiler.xml
- .idea/render.experimental.xml
- mobile/build.gradle
- mobile/src/foss/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/res/drawable/ic_calendar_clock_24dp.xml
- mobile/src/main/res/layout/widgetlist_datetimeinputitem.xml
- mobile/src/main/res/layout/widgetlist_datetimeinputitem_compact.xml
- mobile/src/main/res/layout/widgetlist_icontext_compact.xml
- mobile/src/main/res/layout/widgetlist_iconvaluetext_compact.xml
- mobile/src/main/res/layout/widgetlist_inputitem.xml
- mobile/src/main/res/layout/widgetlist_inputitem_compact.xml
closes [#3285](https://github.com/openhab/openhab-android/issues/3285)
depends on [#3431](https://github.com/openhab/openhab-core/pull/3431)
This PR adds support for the new input widget to the android app.
This is my first time writing for an Android app and writing code in Kotlin. So I will need help to get this finalized, but I hope this is a good basis to start.
I have been running the app in an Android emulator from Android studio, not on a real device. The full syntax is supported (see the BasicUI PR [#1787](https://github.com/openhab/openhab-webui/pull/1787) for my test data and expected behaviour).
Note you will need to run a core with the core PR included to be able to test this.
Known issues at this point observed in the emulator, probably due to my limited understanding of …
> support for Input widget

- mobile/src/main/AndroidManifest.xml
Closes #3354
Android still requires authentication when the setting 'Require screen to be unlocked' is enabled.
> Show activities launched by device control on lock screen

- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
* Ignore icon source and icon set when setting device control icon
* Support Item.Tag.RadiatorControl
* Better handling for Items with 'Control' and another tag
> Improve icons in device control tiles

- mobile/src/main/java/org/openhab/habdroid/ui/homescreenwidget/ItemUpdateWidget.kt
- mobile/src/main/res/layout/widget_item_update_small.xml
It seems that setting `alpha` via code is causing issues on some API
levels. As it is deprecated anyway, use the replacement `imageAlpha`,
which works on all API levels.
Closes #3387
> Fix widgets on API < Android 12

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetDetailBottomSheets.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetSlider.kt
When dealing with UoM, item state may not have the user's preferred unit (e.g. the default setup for percentages in OH4 may be '0.45' for item state and '45%' for widget state when not explicitly having set unit metadata)
Also apply the same change for fetching sitemap icons.
> Prefer widget state over item state when dealing with numbers in sitemap

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
The server expects to be able to parse the passed state as number, which is not possible in e.g. German locale: in that case, e.g. '20,0 °C' instead of the expected '20.0 °C' was passed.
Fixes #3472
> Don't use device locale when formatting state for icons

- mobile/src/main/res/layout/widgetlist_icontext_for_heavy_data.xml
Make icon and font smaller to match what we used for MapView prior to commit 527cd275f32745054ec4532dc3f18493f4261dd9.
See https://github.com/openhab/openhab-webui/issues/2065#issuecomment-1720807556 for a screenshot and rationale.
> Adjust image/chart/map/video header line

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/AbstractItemPickerActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/LogActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
Do enableDrawingBehindStatusBar() unconditionally, as otherwise our app bar will be laid out on top of the status bar.
> Fix status bar being invisible in chart and image activities

- mobile/src/full/java/org/openhab/habdroid/ui/MapViewHelper.kt
If the map isn't loaded yet when the first map widget is bound, the bind attempt for that widget was discarded. Fix this by making sure to apply the widget bind attempt after initially loading the map. While at it, also make sure not to load the map until after the data saver check happened to not cause data transfer before that check.
Fixes #3412
> Fix applying first map location

- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
TYPE_SHUTTER has the same icon as TYPE_WINDOW. It's also not animated, compared to TYPE_BLINDS.
Use the same icon for `blinds` and `rollershutter` as they are the same in the classic icon set as well.
> Item control: Don't use TYPE_SHUTTER

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
While debugging issues with color items I discovered that two SSE events are sent when a slider with a color item is updated.
Item:
````
label: Debug Color 1
type: Color
category: oh:mdi:palette
groupNames: []
groupType: None
function: null
tags: []
````
Sitemap:
````
Slider item=D_Color iconcolor=["itemValue"]
````
The first event contains a state in the hsb format (`10,10,10`), the second events contains the brightness only (`10`). Parsing an integer as brightness failed and the slider was set to `0`.
IMO an integer in the range `0..100` can be considered as brightness.
> Fix brightness parsing

- mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt
I've seen the HTTP code 500 a few times when no connection could be established, so retry in this case.
https://community.openhab.org/t/android-app-item-update-error-http-500-in-case-of-no-connection/149488
> Retry work in case of HTTP code 500

- mobile/src/main/AndroidManifest.xml
It's required, because we have foreground services with this type.
> Add missing permission FOREGROUND_SERVICE_TYPE_DATA_SYNC

- .idea/kotlinc.xml
- mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button_compact.xml
- mobile/src/main/res/values/dimens.xml
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
Closes #3493
First switch has two mappings, second one 4 (with one invalid icon name) and the last two mappings with text only:
> Implement icon in button mappings

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
This uses the new labelSource JSON response field introduced in openhab-core#3804. If the element isn't present (for older server versions), we'll hide the label by default.
> Only show chart/image/video label if specified in sitemap

- .gitattributes
- .idea/dictionaries/openhab.xml
- mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/layout/widgetlist_buttongriditem.xml
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
> Implement buttongrid

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
- mobile/src/test/java/org/openhab/habdroid/model/IconResourceTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/SitemapTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
Resolves #3339  
Perform translations to request material and f7 icons from iconify:
material:iconname -> iconify:ic:baseline-iconname
material:set:iconname -> iconify:ic:set-iconname
f7:iconname -> iconify:f7:iconname
> Support f7, material, and iconify icons

- mobile/src/main/res/values/strings.xml
The user facing name of notification channels is notification categories. I updated the other strings in my previous PR, but missed this one.
> Update notification related string

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
sending icon requests, if available. Apparently this is wrong and we always need to use the item state for fetching icons, so roll back the respective code.
Fixes #3564
> Only use item state when fetching icons

- mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
The UI command item in Main UI uses the same URL for `navigate:` than Main UI itself.
Therefore use the same URLs as the browser uses. When a Basic UI URL is detected, open it in Sitemap, otherwise in Main UI Webview.
Closes #3140
Closes #3529
> Custom targets for device control

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
f7 icons use underscores. When they're imported into iconify, the underscores became dashes.
When user actually specified `f7:icon_name` it should work without them having to know that we implemented it with iconify.
Alternatively users can use `iconify:f7:icon-name` with dashes.
If they had specified `f7:icon-name` that would still to work too.
> Translate f7 underscores into iconify style dashes

- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
When transmitting item state for fetching icons, we must not use state formatting, but either use the plain numeric value or "<value> <unit>".
Fixes #3606
> Remove any state description dependencies when fetching icon state

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
One use case for this are items bound to channels of type system.signal-strength. Those are number items with a default pattern of %0.f and options mapping the valid values 0..4 to descriptive strings. Show those descriptive strings (e.g. 'Excellent') if available instead of the plain number value ('4').
> Consider mappings or options for displayed state

- mobile/src/main/java/org/openhab/habdroid/ui/AbstractBaseActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
The root view must not set `android:animateLayoutChanges="true"`.
https://github.com/material-components/material-components-android/issues/648
Closes #3393
> Fix flickering snackbar

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/res/values/strings.xml
Add an entry to the context menu that allows showing a chart on a new screen. It's possible to display charts for all Items in Main UI settings and this is quite useful. The word 'Analyze' is also taken from Main UI.
(Screenshot from German device)
> Show charts for all Sitemap widgets

- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
> Potential fix for #3637 / race condition sitemap vs events

- mobile/build.gradle
- mobile/src/foss/java/org/openhab/habdroid/core/NotificationPoller.kt
- mobile/src/full/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationWorker.kt
- mobile/src/main/java/org/openhab/habdroid/core/NotificationHelper.kt
- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
> Update firebase to latest version

- mobile/src/beta/res/xml/day_dream.xml
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/DayDream.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/DayDreamPreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/PreferencesActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/DayDreamFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/layout/daydream.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences_day_dream.xml
- mobile/src/stable/res/xml/day_dream.xml
Add a simple daydream service that displays a clock and the text from a custom Item. The implementation is kept simple as there might be a screen saver in Android 15 that utilizes the device controls: https://www.androidauthority.com/android-15-home-controls-screensaver-3433352/
Closes #215
> Add screensaver (daydream)

- .gitignore
- .idea/kotlinc.xml
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerConfiguration.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/MainUiWebViewFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/ServerEditorFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/PrefKeys.kt
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/xml/preferences_server.xml
> Allow configuration of MainUI start page

- .github/workflows/lint.yml
All required linters are part of the slim variant: https://github.com/super-linter/super-linter?tab=readme-ov-file#super-linter-variants
> Use slim version of super-linter

- mobile/src/main/java/org/openhab/habdroid/ui/preference/widgets/CustomInputTypePreference.kt
- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
- mobile/src/main/java/org/openhab/habdroid/util/CacheManager.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
> Prior to the introduction of entries in Kotlin 1.9.0, the values() function was used to retrieve an array of enum constants.
from https://kotlinlang.org/docs/enum-classes.html#working-with-enum-constants
> Replace Enum.values() by Enum.entries

- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
Update Sitemaps in drawer when they are fetched. This avoids the flicker when the drawer is opened, because no update happens then (at least if there are no new Sitemaps on the server).
> Avoid flicker when opening drawer

- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/MainSettingsFragment.kt
Populate server prefs earlier, so they don't get animated when opening settings.
> Avoid animation of server settings

- mobile/src/main/java/org/openhab/habdroid/ui/DayDream.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ItemClient.kt
Avoid ANR by not trying to get events from a closed subscription. Instead wait 5 seconds and create a new channel then.
> Improve SSE error handling

- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ImageWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ItemClient.kt
I see some crashes due to HttpException in Firebase, but there's no origin visible. This PR adds a few more try/catch blocks around network calls. Let's see if that fixes all crashes.
> Catch more HttpException

- mobile/src/main/res/layout/activity_item_picker.xml
- mobile/src/main/res/layout/fragment_notificationlist.xml
- mobile/src/main/res/layout/fragment_webview.xml
In the notification list the German translation of the error message requires two lines and thus is left aligned.
> Center error messages

- mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt
I noticed that myopenhab.org sometimes returns http code 200 for an icon and a valid svg content type, but the content length is 0. In that case, change to http code to 500 to avoid caching.
Fixes #3733
> Don't cache responses with 0 content length

- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
- mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
- mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/ItemClient.kt
- mobile/src/test/java/org/openhab/habdroid/model/IconResourceTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.kt
openHAB 2 has been 7 years ago, so it should be fine to drop support for openHAB 1 now.
https://www.openhab.org/blog/2017-01-22-openhab2.html
> Drop support for openHAB 1

- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.kt
This supports having a buttongrid + buttons inside a frame, because the Buttons are sub-widgets which are normally excluded due to being the grand children of the first level.
> Fix Buttons not showing when the Buttongrid is inside a Frame

- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
Fix #3756
The problem was:
- StringItem's state contains `[]`
- Sitemap puts the item's (display) state into the label as `Label [formattedstate]`
- So now we have nested `[]` causing parsing errors when trying to extract the formattedstate from `[mytext with [] in it]`.
> Fix stateFromLabel when label contains square brackets in pattern

- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/res/drawable/frame_nested_chip_background.xml
- mobile/src/main/res/layout/widgetlist_frameitem_nested.xml
- mobile/src/main/res/layout/widgetlist_frameitem_nested_compact.xml
```
sitemap nestedframe {
Frame label="outer" {
Frame label="inner1" {
Text label="Text inside inner1"
}
Frame label="inner2" {
Text label="Text inside inner2"
}
}
Frame label="outer too" {
Text label="Inside outer too"
}
}
```
I learned that nested frames aren't "supposed" to be supported, but BasicUI and iOS renders them, whilst Android doesn't.
Here, I propose to render nested frames, and also provide a visual clue for the nesting structure by using `colorTertiaryContainer`, indenting the header text and reduce the header bg's height/padding, as suggested by @maniac103 
Resolve #324, #1639, #2804
Also [#420 ](https://github.com/openhab/openhab-webui/issues/420)
> Allow one level of nested frames in sitemaps

- mobile/src/main/res/layout/widgetlist_iconvaluetext.xml
The widget value is capped to 3 lines, which might not be enough space for some Text items with longer text, e.g. weather warnings (https://www.openhab.org/addons/bindings/dwdunwetter/). I don't see a reason why the value should be truncated.
This only applies to the default layout. For the compact layout, it's still limited to one line.
> Don't truncate widget values

- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
I personally use only the title for most notifications, so I discovered a crash when using the following code to create a notification:
```js
actions.notificationBuilder()
.withTitle("foo")
.send();
```
There's no message passed to `notificationBuilder()`. In this case, handle it like an empty string as message.
> Fix notifications without message

- mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.kt
- mobile/src/main/res/values/attrs.xml
This broke when WidgetImageView was changed to no longer be derived from ImageView in #3787. Since WidgetImageView passes all view attributes to its internal ImageView instance, let the framework know that this is the case.
> Fix tools:src not working for WidgetImageView

- mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt
- mobile/src/main/java/org/openhab/habdroid/core/UpdateBroadcastReceiver.kt
- mobile/src/main/java/org/openhab/habdroid/model/CloudNotification.kt
- mobile/src/main/java/org/openhab/habdroid/model/IconResource.kt
- mobile/src/main/java/org/openhab/habdroid/model/Item.kt
- mobile/src/main/java/org/openhab/habdroid/model/LabeledValue.kt
- mobile/src/main/java/org/openhab/habdroid/model/LinkedPage.kt
- mobile/src/main/java/org/openhab/habdroid/model/ServerProperties.kt
- mobile/src/main/java/org/openhab/habdroid/model/Sitemap.kt
- mobile/src/main/java/org/openhab/habdroid/model/Widget.kt
- mobile/src/main/java/org/openhab/habdroid/model/WidgetDataSource.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ItemPickerAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/activity/PageConnectionHolderFragment.kt
- mobile/src/main/java/org/openhab/habdroid/ui/preference/fragments/WidgetSettingsFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/java/org/openhab/habdroid/util/ItemClient.kt
- mobile/src/test/java/org/openhab/habdroid/model/IconResourceTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/ItemTest.kt
- mobile/src/test/java/org/openhab/habdroid/model/WidgetTest.kt
- mobile/src/test/java/org/openhab/habdroid/util/UtilTest.kt
Reverts openhab/openhab-android#3725
> Revert "Drop support for openHAB 1"

- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button.xml
- mobile/src/main/res/layout/widgetlist_sectionswitchitem_button_compact.xml
That tint overwrote both the icon coloring and the iconcolor attribute.
Fixes #3815
> Clear default button icon tint

- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
The fallback color was black, so the icons were nearly invisible in dark mode.
Closes #3826
> Fix invisible buttongrid icons

- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
- mobile/src/main/java/org/openhab/habdroid/background/EventListenerService.kt
- mobile/src/main/java/org/openhab/habdroid/core/OpenHabApplication.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WriteTagActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
> Increase targetSdk to 34

- mobile/src/foss/java/org/openhab/habdroid/core/CloudMessagingHelper.kt
- mobile/src/main/java/org/openhab/habdroid/ui/CloudNotificationListFragment.kt
Now notifications can be hidden by other notifications which might require that fetching 20 notifications isn't enough to fill one page. Thus increase the page size to 50.
Also see #3837
> Increase notification API page size

- mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt
It doesn't seem correct to send Item updates that have been triggered before a reboot.
Other background tasks are enqueued again anyway, so this should only cancel widgets, NFC and Tasker.
Closes #3859
> WorkManager: cancel after reboot

- mobile/build.gradle
Seems to be a bug in latest WorkManager version:
```
java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
at androidx.work.Data$getStringArray$$inlined$getTypedArray$1.invoke(Data_.kt:65)
at androidx.work.Data$getStringArray$$inlined$getTypedArray$1.invoke(Data_.kt:65)
at androidx.work.Data.getStringArray(Data_.kt:185)
at org.openhab.habdroid.background.ItemUpdateWorkerKt.getValueWithInfo(ItemUpdateWorker.kt:411)
at org.openhab.habdroid.background.ItemUpdateWorker.doWork(ItemUpdateWorker.kt:76)
at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:67)
at androidx.work.CoroutineWorker$startWork$1.invoke(Unknown Source:8)
at androidx.work.CoroutineWorker$startWork$1.invoke(Unknown Source:4)
```
> Fix NPE in WorkManager

- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionManagerHelper.kt
- mobile/src/main/java/org/openhab/habdroid/core/connection/DefaultConnection.kt
- mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/test/java/org/openhab/habdroid/core/connection/ConnectionFactoryTest.kt
Use non-deprecated functions, and restart connection check in `MainActivity.onStart()`.
> Refactor connection handling for API 31+

- mobile/build.gradle
- mobile/src/main/AndroidManifest.xml
- mobile/src/main/java/org/openhab/habdroid/ui/ChartImageActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt
- mobile/src/main/java/org/openhab/habdroid/ui/WidgetListFragment.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
- mobile/src/main/res/layout/activity_chart.xml
- mobile/src/main/res/layout/activity_chartimage.xml
- mobile/src/main/res/layout/chart_marker.xml
- mobile/src/main/res/values-night/themes.xml
- mobile/src/main/res/values-v23/themes.xml
- mobile/src/main/res/values/arrays.xml
- mobile/src/main/res/values/attrs.xml
- mobile/src/main/res/values/strings.xml
- mobile/src/main/res/values/themes.xml
This one uses the persistence REST API and replaces the one showing a larger server-side generated chart image if supported (that is, for OH >= 2). It uses client-side chart rendering, the advantage of which is the possibility of zooming into the chart data and getting tooltips for values.
> Add interactive chart activity

- mobile/src/main/java/org/openhab/habdroid/model/ParsedState.kt
In that case the 'state' part of the item response has no unit (e.g. '12'), but the format pattern still contains the unit (e.g. '%.0f %unit%'), in which case we sent commands like '15 ' to the server, which it rejected. Make sure to omit the space in that case.
Fixes #3882
> Make sure to format number values correctly for unit 'one'

- mobile/src/main/java/org/openhab/habdroid/ui/ChartWidgetActivity.kt
- mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt
Despite compression, chart data size still can be too large, thus change the approach: instead of caching the data in the saved instance state, cache it in a retained fragment.
> Fix occasional crashes when stopping chart activity
